### PR TITLE
Fix new block and new transaction buttons - Closes #3643

### LINKED ISSUE #3643: New block and new transaction buttons do not appear
### Expected behavior
- The new block button in monitor/blocks page should show up when there's a new block.
- The new transaction button in monitor/transactions page should show up when there's a new transaction.

### Actual behavior
They never appear.

### Steps to reproduce
- Visit monitor/blocks and monitor/transactions.
- Keep the page open for a while.

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?
This PR resolves #3643

### How was it solved?
The subscriber was outdated and didn't work with the new API structure. It must have been broken since 2.0.0-beta.0. I removed the outdated hooks and used the latest blocks data from the Redux store to display the buttons.

### How was it tested?
Unit tests are updated and the app is tested manually.

### CODE REVIEW

File: src/components/screens/monitor/blocks/blocks.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ const Blocks = ({
           <BlockFilterDropdown filters={filters} applyFilters={applyFilters} />
         </BoxHeader>
         <LoadLatestButton
-          event="update.block"
+          entity="block"
```
Comment (isalga) [inline src/components/screens/monitor/blocks/blocks.js:56]: Can we make this "block" string a constant and import it? That would be more scalable and not prone to crash.

**Review by isalga — CHANGES_REQUESTED** [review]

File: src/components/screens/monitor/blocks/blocks.js (hunk 1 above)
Comment (reyraa) [reply src/components/screens/monitor/blocks/blocks.js:56]: I do agree we should prevent mistakes there, but I think propTypes is a better choice than constants.

**Review by isalga — APPROVED** [review]

**Review by isalga — APPROVED** [review]
