### PR TITLE
Fix validator and application overview visual issues and validator profile navigation issues

### LINKED ISSUE #5008: Visual bugs in validators and generation details view
### Expected behavior

- Missed slots colour must've been in grey
- Round state icon should be displayed

### Actual behavior

- Generated slots and Missed slots have the same colour (green)
- Round state for Generators is displayed empty

image

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #5008, #5007 and #5009

### How was it solved?
- [x] Fixed chart legend colours
- [x] Updated round state icon display
- [x] Fixed total supply display
- [x] Fixed empty applications table text
- [x] Fixed validator profile back button navigation

### How was it tested?

- Visually

### CODE REVIEW

File: src/modules/pos/validator/components/ValidatorsTable/index.js [hunk 1]
```diff
@@ -35,7 +45,7 @@ const ValidatorsTable = ({ setActiveTab, activeTab, blocks, filters }) => {
     [activeTab, sort, filters]
   );
   const { data: validators } = useValidators({
-    config: { params: { limit: 103, status: 'active' } },
+    config: { params: { limit: ROUND_LENGTH, status: 'active' } },
```
Comment (sameersubudhi) [inline src/modules/pos/validator/components/ValidatorsTable/index.js]: I'd recommend keeping it as 103, since that's the max limit the API supports. Or, if using the `ROUND_LENGTH`, apply paginated query technique to fetch all the data, since a custom application can possible have a much larger round and this query then will return validation errors from Lisk Service.

```suggestion
    config: { params: { limit: 103, status: 'active' } },
```

**Review by sameersubudhi — DISMISSED** [review]
Haven't ran the code but the edits look fine. Also, please consider the following recommendation.

File: src/modules/pos/validator/components/ValidatorsTable/index.js (hunk 1 above)
Comment (ikem-legend) [reply src/modules/pos/validator/components/ValidatorsTable/index.js]: @sameersubudhi Fixed

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

**Review by ManuGowda — APPROVED** [review]
