### PR TITLE
Fix wrong information displayed in Delegates Monitor - Closes #3684

### LINKED ISSUE #3684: Wrong information in Delegates Monitor page
### Expected behavior
- The number of forged blocks must match with the round status graph.
- The round state and forging time must match the new blocks forged. 

### Actual behavior
- The number of forged blocks is shown as blocks created minus missed slots, which is incorrect.
- There are too many forgers who missed their slot, but that doesn't match the new blocks sent over WS.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-rc.2

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?
This PR resolves #3684

### How was it solved?
- [x] Filter out the new blocked that were emitted multiple times.
- [x] The numbers displayed and slot status and round status graphs must match.

### How was it tested?
Visually
Compare the numbers with the values of the blocks page.

### CODE REVIEW

File: src/components/screens/monitor/delegates/overview/forgingDetails.js [hunk 1]
```diff
@@ -15,17 +15,9 @@ import styles from './overview.css';
...
 
-const getForgingStats = (data, forgedInRound) => {
-  if (forgedInRound === 0) return [0, 103, 0];
-  const states = {
-    forging: 0,
-    awaitingSlot: 0,
-    missedBlock: 0,
-  };
-  data.forEach((item) => {
-    states[item.state] += 1;
```
Comment (UsamaHameed) [inline src/components/screens/monitor/delegates/overview/forgingDetails.js:26]: Nice algorithm we have got here 💯

File: src/components/screens/monitor/delegates/overview/forgingDetails.js [hunk 2]
```diff
@@ -15,17 +15,9 @@ import styles from './overview.css';
...
-  });
-  return [states.forging, states.awaitingSlot, states.missedBlock];
+const getForgingStats = (data, forgedInRound = 0) => {
+  const missedBlock = data.filter(item => item.state === 'missedBlock').length;
+  return [forgedInRound, ROUND_LENGTH - forgedInRound, missedBlock];
```
Comment (UsamaHameed) [inline src/components/screens/monitor/delegates/overview/forgingDetails.js:20]: Would be great if you can rename this to `missedBlocks`, it better represents what it holds

**Review by UsamaHameed — APPROVED** [review]
