### PR TITLE
Bugfix: Fix electron renderer permission checks

### LINKED ISSUE #5118: Lack of permission checks in the Electron application
### Description

The code does not use the setPermissionRequestHandler function to prevent the renderer from accessing systems such as using the webcam and notification system. 

As specified in Electron’s documentation: By default, Electron will automatically approve all permission requests unless the
developer has manually configured a custom handler. While a solid default, security-conscious developers might want to assume the very opposite.

This is the opposite of a browser such as Chrome who asks the user for permission. Inlisk-desktop this is not the case and may allow an attacker who can inject javascript in the application to silently record audio and video.

### Reference

https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5118

### How was it solved?

- [x] Added permission to be whitelisted (i.e allowed)

### How was it tested?

- Run `yarn dev`
- Run `yarn build:electron && yarn start`
- In the dev tool of the resulting electron browser request media permissions by executing the below snippet in the browser's console

```
navigator.getUserMedia ( {
      video: true,
      audio: true
   },
   function(localMediaStream) { console.log("Permission granted") },
   function(err) { console.log("Permission rejected") }
);
```
(Permissions should be rejected)

- Also try to read clipboard text by executing `navigator.clipboard.readText()` in the electron browser's console, permission should be granted.

### CODE REVIEW

**Review by oskarleonard — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]

**Comment by ManuGowda** [comment]
Screenshot 2023-07-06 at 10 27 58 AM

I am using the release branch and without above change also the permission was denied 🤔

File: app/src/utils.js [hunk 1]
```diff
@@ -16,3 +18,9 @@ export const isValidAddress = (address) =>
 export const getBufferToHex = (buffer) => cryptography.utils.bufferToHex(buffer);
 
 export const getTransactionBytes = (transaction) => transaction.getBytes(transaction);
+
+export const setRendererPermissions = (win) => {
+  win.browser.webContents.session.setPermissionRequestHandler((_, permission, callback) => {
```
Comment (ManuGowda) [inline app/src/utils.js:23]: https://www.electronjs.org/docs/latest/tutorial/security#5-handle-session-permission-requests-from-remote-content

probably follow the electron recommendation?

Comment (ManuGowda) [reply app/src/utils.js:23]:
```
const { session } = require('electron')
const { URL } = require('url')

session
  .fromPartition('some-partition')
  .setPermissionRequestHandler((webContents, permission, callback) => {
    const parsedUrl = new URL(webContents.getURL())

    if (permission === 'notifications') {
      // Approves the permissions request
      callback(true)
    }

    // Verify URL
    if (parsedUrl.protocol !== 'https:' || parsedUrl.host !== 'example.com') {
      // Denies the permissions request
      return callback(false)
    }
  })
```

**Review by ManuGowda — CHANGES_REQUESTED** [review]

**Review by ManuGowda — APPROVED** [review]
