### PR TITLE
Fix unit test env issues - Closes #3539

### LINKED ISSUE #3539: Improve code separation and jest config
### Expected behavior
Since node crashes the process with a non zero error code if code results in an UnhandledPromiseRejection. Our jest tests and code in general has been working because this was just a `warning` and not an `error` before. Now that we updated our node, react and jest versions, we need to handle promise rejections better.

### Actual behavior
Promise rejections are not handled or handled poorly.

### PR DESCRIPTION
**Pull request by UsamaHameed**
### What was the problem?
This PR resolves #3539 

### How was it solved?
- Introduce better separation between react components and constants
- Fix tests and use better mocks
- Ignore promise rejection for now (to be fixed in #3485)

### How was it tested?
Unit tests + eslint

### CODE REVIEW

File: config/setupJest.js [hunk 1]
```diff
@@ -190,3 +190,11 @@ jest.mock('react-chartjs-2', () => ({
   Doughnut: () => null,
   Bar: () => null,
 }));
+
+global.fetch = jest.fn(() =>
```
Comment (UsamaHameed) [inline config/setupJest.js:194]: We need a mock for `window.fetch` in jest because jest is a node process and window.fetch is undefined.

File: src/components/screens/dashboard/recentTransactions/recentTransactions.js [hunk 2]
```diff
@@ -3,7 +3,7 @@ import { withTranslation } from 'react-i18next';
 import { useSelector } from 'react-redux';
 import { Link } from 'react-router-dom';
 
-import { selectAccount, selectCurrentBlockHeight } from '@store';
+import { selectAccount, selectCurrentBlockHeight } from '@store/selectors';
```
Comment (UsamaHameed) [inline src/components/screens/dashboard/recentTransactions/recentTransactions.js:6]: Helps import only the selectors and not the other files from `@store` like middlewares and reducers.

File: src/components/screens/multiSignature/editor/editor.test.js [hunk 3]
```diff
@@ -1,7 +1,38 @@
 import React from 'react';
 import { mount } from 'enzyme';
+
+import { getTransactionBaseFees, getTransactionFee } from '@api/transaction';
+import useTransactionFeeCalculation from '@shared/transactionPriority/useTransactionFeeCalculation';
+import { fromRawLsk } from '@utils/lsk';
+
 import Editor from './editor';
 
+jest.mock('@shared/transactionPriority/useTransactionFeeCalculation');
```
Comment (UsamaHameed) [inline src/components/screens/multiSignature/editor/editor.test.js:10]: Now that node does not warn and instead fails with `process.exit(~0)` on unhandledPromiseRejections, our test setups have to be better. This fee calculation mock was missing.

File: src/components/screens/send/form/form.test.js [hunk 4]
```diff
@@ -2,10 +2,40 @@ import React from 'react';
...
 import { mount } from 'enzyme';
 import { tokenMap, moduleAssetSchemas } from '@constants';
+import { getTransactionBaseFees, getTransactionFee } from '@api/transaction';
+import useTransactionFeeCalculation from '@shared/transactionPriority/useTransactionFeeCalculation';
+import { fromRawLsk } from '@utils/lsk';
 import Form from './form';
 import accounts from '../../../../../test/constants/accounts';
 import flushPromises from '../../../../../test/unit-test-utils/flushPromises';
 
+jest.mock('@shared/transactionPriority/useTransactionFeeCalculation');
```
Comment (UsamaHameed) [inline src/components/screens/send/form/form.test.js:12]: Same as: https://github.com/LiskHQ/lisk-desktop/pull/3537/files#r628003984

File: src/components/screens/votingQueue/editor/editor.test.js [hunk 5]
```diff
@@ -2,10 +2,39 @@ import { act } from 'react-dom/test-utils';
...
 
 import { mountWithRouter } from '@utils/testHelpers';
+import { getTransactionBaseFees, getTransactionFee } from '@api/transaction';
+import useTransactionFeeCalculation from '@shared/transactionPriority/useTransactionFeeCalculation';
+import { fromRawLsk } from '@utils/lsk';
 import accounts from '../../../../../test/constants/accounts';
 import flushPromises from '../../../../../test/unit-test-utils/flushPromises';
 import Editor from './editor';
 
+jest.mock('@shared/transactionPriority/useTransactionFeeCalculation');
```
Comment (UsamaHameed) [inline src/components/screens/votingQueue/editor/editor.test.js:12]: Same as: https://github.com/LiskHQ/lisk-desktop/pull/3537/files#r628003984

File: src/constants/routes.js [hunk 6]
```diff
@@ -1,137 +1,89 @@
-import AddBookmark from '@screens/bookmarks/addBookmark';
```
Comment (UsamaHameed) [inline src/constants/routes.js:1]: This file does not import any React components anymore and is truly a constants file. So, whenever a test imports `@constants`, no components will be included in the code executed by jest.

File: src/routesMap.js [hunk 7]
```diff
@@ -0,0 +1,70 @@
+import AddBookmark from '@screens/bookmarks/addBookmark';
```
Comment (UsamaHameed) [inline src/routesMap.js:1]: This file defines a map of route names to their equivalent components

File: src/utils/api/http.js [hunk 8]
```diff
@@ -37,7 +38,9 @@ const http = ({
         return response.json();
       });
   } catch (e) {
-    return Promise.reject(Error(e));
+    // eslint-disable-next-line no-console
+    console.error(e);
+    // return Promise.reject(Error(e));
```
Comment (UsamaHameed) [inline src/utils/api/http.js:43]: I have temporarily removed this promise rejection since its not being handled anyway. We have plans to introduce better error handling in #3485

File: src/utils/api/network/lsk.js [hunk 9]
```diff
@@ -49,7 +49,7 @@ export const getNetworkConfig = ({ name, address }) => {
     .catch((err) => {
       // eslint-disable-next-line no-console
       console.error(err);
-      throw Error(`Can not connect to ${address}`);
+      // throw Error(`Can not connect to ${address}`);
```
Comment (UsamaHameed) [inline src/utils/api/network/lsk.js:52]: Same as: https://github.com/LiskHQ/lisk-desktop/pull/3537/files#r628007049

**Review by isalga — APPROVED** [review]

**Review by reyraa — APPROVED** [review]

**Comment by reyraa** [comment]
Thanks for all the comments. Really helped.
