### PR TITLE
Sign msing steps, edit bookmark, account cration - Closes #3624,#3625,#3628

### LINKED ISSUE #3624: Sign multisignature transaction steps are not indicated properly
### Expected behavior

The current step is correctly indicated.

### Actual behavior

The step remains at 1, even though it is actually step 2.

Screenshot 2021-06-20 at 13 57 58

Once you have signed the multisignature transaction it correctly shows step 3 as the current and final step.

### Steps to reproduce

Given an unsigned multisignature transaction:

1. From the sidebar, click on the `Sign multisignature` option
2. Paste (or uploaded) a multisignature transaction
3. Observe the step remains at 1
3. Sign the transaction
3. Observe the step moves to 3 (skipping 2)

### Which version(s) does this affect? (Environment, OS, etc...)

- `v2.0.0-beta.4`

### PR DESCRIPTION
**Pull request by isalga**
### What was the problem?
This PR resolves #3624, #3625, #3628

### How was it solved?
Update UI and fix styling issues

### How was it tested?
Visually

### CODE REVIEW

File: src/components/toolbox/steppedProgressBar/steppedProgressBar.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import styles from './styles.css';
 
 const Step = ({ children, current, active }) => (
   <span className={
-    [styles.step, current ? styles.current : '', active ? styles.active : '']
```
Comment (reyraa) [inline src/components/toolbox/steppedProgressBar/steppedProgressBar.js:7]: I was expecting eslint to block complex ternaries.

File: src/components/screens/bookmarks/list/list.js [hunk 2]
```diff
@@ -229,7 +230,9 @@ export class BookmarksList extends React.Component {
                                   ? (
                                     <TertiaryButton
                                       onClick={e => this.editBookmark(e, bookmark)}
-                                      className="bookmarks-edit-button"
+                                      className={
+                                        `bookmarks-edit-button ${bookmark.isDelegate && styles.hide}`
```
Comment (reyraa) [inline src/components/screens/bookmarks/list/list.js:234]: `bookmarks-edit-button ${bookmark.isDelegate ? styles.hide : ''}`

Comment (reyraa) [reply src/components/screens/bookmarks/list/list.js:234]: So there's no `false` in the className string

**Review by reyraa — APPROVED** [review]
