### PR TITLE
Send token button should be disabled when available balance is 0

### LINKED ISSUE #5197: Send token button should be disabled when available balance is 0
### Expected behavior

Send token button should be disabled when available balance is 0

### Actual behavior

User is able to open the send form when an account do not have available balance

### Steps to reproduce

- Create an account
- Add account to wallet
- `Send` button is not disabled

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5197

### How was it solved?

- Disable `send` button
- Removed unused components and functions

### How was it tested?

- Create an account with 0 balance

### CODE REVIEW

File: src/modules/blockchainApplication/manage/hooks/useSearchApplications.js [hunk 1]
```diff
@@ -18,7 +25,7 @@ export const useSearchApplications = () => {
   const setDebounceSearch = (value) => {
     setSearchValue(value);
     clearTimeout(timeout.current);
-    // Validate the URL with debouncer
+    // Validate the URL with denouncer
```
Comment (oskarleonard) [inline src/modules/blockchainApplication/manage/hooks/useSearchApplications.js]: isnt it `debouncer` ?

File: src/modules/wallet/components/AllTokens/AllTokens.js [hunk 2]
```diff
@@ -1,5 +1,6 @@
 /* eslint-disable max-statements */
 import React, { useCallback, useMemo, useRef, useState } from 'react';
+import { useLocation } from 'react-router';
```
Comment (oskarleonard) [inline src/modules/wallet/components/AllTokens/AllTokens.js]: I think we should only import from  `react-router-dom`, and when migration is complete remove, `react-router` completely from our package.json. `react-router-dom` is a super-set of `react-router`, no need for both

File: src/modules/wallet/components/AllTokens/AllTokens.js [hunk 3]
```diff
@@ -29,8 +28,13 @@ const AllTokens = ({ history }) => {
   const { t } = useTranslation();
   const timeout = useRef();
 
-  const [search, setSearch] = useState('');
+  const [searchToken, setSearch] = useState('');
   const { filters, setFilter } = useFilter({});
+  const { search } = useLocation();
+  const queryParams = new URLSearchParams(search);
+  const disableSend = Boolean(queryParams.get('disableSend'));
```
Comment (oskarleonard) [inline src/modules/wallet/components/AllTokens/AllTokens.js]: Doesnt this query param contain a string representation of 'true' or 'false'? 
In that case we cannot rely on `Boolean(` since 
image

Better to do:
`const isSendDisabled = queryParams.get('disableSend') === 'true';`
🤔

Comment (oskarleonard) [reply src/modules/wallet/components/AllTokens/AllTokens.js]: As you can see here: 
image

**Review by ikem-legend — DISMISSED** [review]

**Review by ikem-legend — APPROVED** [review]

**Review by oskarleonard — APPROVED** [review]
