### PR TITLE
Fix Staking and network switch issues

### LINKED ISSUE #4954: Removing a stake shows wrong label
### Expected behavior
When removing/decreasing a stake should have correct label

### Actual behavior
When removing a stake the next modal should not say “Stake added”
image

And this modal should not say 20LSK Tokens are now staked after having removed a stake
image

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4954, #4953, #4955, #4966, #3757, #4952

### How was it solved?

- [x] Fix texts in staking modals
- [x] Fix irregular sorting on staks table
- [x] Fix network switching freeze on ApplicationBootstrap
- [x] Fix UI/UX and stakes
- [x] Change onClick to onMouseDown on dialog component
- [x] Resolve failing unit test

### How was it tested?

- Visually

### CODE REVIEW

**Review by oskarleonard — DISMISSED** [review]

File: src/modules/pos/validator/components/StakeStatus/statusMessages.js [hunk 1]
```diff
@@ -7,13 +7,13 @@ import styles from './styles.css';
 
 const unlockTime = 5;
 
-const LiskAmountFormatted = ({ val }) => (
+const LiskAmountFormatted = ({ val, token }) => (
   <span className={styles.subHeadingBold}>
-    <TokenAmount isLsk val={val} />
+    <TokenAmount isLsk val={val} token={token} />
```
Comment (ManuGowda) [inline src/modules/pos/validator/components/StakeStatus/statusMessages.js]: `isLsk` this could be a bug? what if collecti or other sidechain uses pos consensus and token wont be LSK? since you are passing `token` explicitly it should be handled dynamically?

**Review by ManuGowda — CHANGES_REQUESTED** [review]

File: src/modules/pos/validator/components/StakeStatus/statusMessages.js (hunk 1 above)
Comment (eniolam1000752) [reply src/modules/pos/validator/components/StakeStatus/statusMessages.js]: `token={token}` overrides `isLisk` but yea you are correct `isLisk` should be removed

**Review by ManuGowda — DISMISSED** [review]

**Review by ManuGowda — DISMISSED** [review]

File: src/modules/pos/validator/components/StakeStatus/Status.js [hunk 2]
```diff
@@ -10,15 +10,15 @@ import statusMessages from './statusMessages';
 import styles from './styles.css';
 import StakeSuccessfulModal from '../StakeSuccessfulModal';
 
-const Status = ({ account, transactions, statusInfo, t, dposToken }) => {
+const Status = ({ account, transactions, statusInfo, t, dposToken}) => {
```
Comment (oskarleonard) [inline src/modules/pos/validator/components/StakeStatus/Status.js]: why was space after dposToken removed?

Comment (eniolam1000752) [reply src/modules/pos/validator/components/StakeStatus/Status.js]: fixed

**Review by oskarleonard — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
