### PR TITLE
Fix missing latest vote properties - Closes #4018

### LINKED ISSUE #4018: The latest vote weight is missing
### Expected behavior
I should be able to see the vote weight of my latest vote and edit it.

### Actual behavior

I can't see my vote weight (the second row) and 

Screenshot 2021-12-14 at 15 49 25

### Which version(s) does this affect? (Environment, OS, etc...)
release/2.2.0

### PR DESCRIPTION
**Pull request by gadjacobs**
### What was the problem?

This PR resolves #4018 

### How was it solved?

- Aligning the table header and row
- Triggering a re-render when the vote list is updated.

### How was it tested?

Visually.

### CODE REVIEW

File: src/components/screens/wallet/votes/votes.js [hunk 1]
```diff
@@ -37,11 +37,11 @@ const Votes = ({
 
   // Fetch delegate profiles to define rank, productivity and delegate weight
   useEffect(() => {
-    if (isEmpty(accounts.data) && votes.data.length) {
-      const addressList = votes.data.map(vote => vote.address);
+    const addressList = Object.keys(hostVotes);
```
Comment (ManuGowda) [inline src/components/screens/wallet/votes/votes.js:40]:
```suggestion
    const addressList = Object.keys(sentVotes);
```

File: src/components/screens/wallet/votes/votes.js [hunk 2]
```diff
@@ -37,11 +37,11 @@ const Votes = ({
...
+    if (isEmpty(accounts.data) && addressList.length) {
       accounts.loadData({ addressList, isDelegate: true });
     }
-  }, [votes.data]);
+  }, [hostVotes]);
```
Comment (ManuGowda) [inline src/components/screens/wallet/votes/votes.js:44]:
```suggestion
  }, [sentVotes]);
```

**Review by ManuGowda — COMMENTED** [review]
Please add tests to cover the scenarios

File: src/components/screens/wallet/votes/votes.js (hunk 2 above)
Comment (gadjacobs) [reply src/components/screens/wallet/votes/votes.js:44]: @ManuGowda `hostVotes` returns both sent and received votes for the selected delegate, so it might be a more appropriate name.

Comment (reyraa) [reply src/components/screens/wallet/votes/votes.js:44]: @gadjacobs This prop is defined as `hostVotes: state.voting` which only includes the votes sent by the account. not the ones they received.

**Review by reyraa — CHANGES_REQUESTED** [review]

**Review by reyraa — APPROVED** [review]
