### PR TITLE
Fix account management and application exploring issues

### LINKED ISSUE #4405: Issues discovered in account management and application exploring
### Description

- No error message is displayed when a wrong password format is provided in the Enter-password form on the add account by secret-recovery passphrase flow

- We need to have the currently selected account highlighted on the added account list

- Alignment is off 
image

### Motivation

These were comments raised during the desktop review for the `Account management` and `Application Exploring` objectives

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #4405, #4409, #4860

### How was it solved?

- [x] Currently selected account should be highlighted on the added account list
- [x] Fix alignment issue in applications table
- [x] Backup account filename should be unique
- [x] `Set up device password` is missing `Go Back` options

### How was it tested?

- Visually
- Unit tests

### CODE REVIEW

**Review by ManuGowda — CHANGES_REQUESTED** [review]
PR looks good to me, backup flow needs minor UI change to align with proposal https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=39-50031&t=Sh1yeCr608Eawya4-4

File: src/modules/account/components/RemoveConfirmation/RemoveConfirmation.js [hunk 1]
```diff
@@ -22,29 +25,22 @@ const RemoveConfirmation = ({
...
-      <WalletVisual
-        className={styles.avatar}
-        address={account?.metadata?.address}
-      />
-      {
-        account?.metadata?.name
-        && (<p className={styles.accountName}>{account?.metadata?.name}</p>)
-      }
+      <WalletVisual className={styles.avatar} address={account?.metadata?.address} />
+      {account?.metadata?.name && <p className={styles.accountName}>{account?.metadata?.name}</p>}
```
Comment (oskarleonard) [inline src/modules/account/components/RemoveConfirmation/RemoveConfirmation.js]: We can use the local variable declared at the top, `accountName`, to prevent us from using two different ones for the same data.

Comment (ikem-legend) [reply src/modules/account/components/RemoveConfirmation/RemoveConfirmation.js]: @oskarleonard Resolved

**Review by ManuGowda — APPROVED** [review]
Great job 👍🏼

**Review by oskarleonard — APPROVED** [review]
