### PR TITLE
Make sender clickable in multiple pages and fix address search and wallet display

### LINKED ISSUE #5043: Can't search for regular accounts
### Expected behavior
User should be able to search for regular accounts
### Actual behavior
It's not possible
image

### Steps to reproduce
search for `lsk4ayx5che3yekr38v6dpbcy25nz63yv387yv6fk` in the search tab

### Which version(s) does this affect? (Environment, OS, etc...)
Desktop 3.0-beta Windows 11

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #5043, #5044 and #5045

### How was it solved?

- [x] Fixed address search
- [x] Added link for transaction sender
- [x] Fixed wallet display for current and searched addresses

### How was it tested?

- Visually
- Unit tests

### CODE REVIEW

File: src/modules/account/components/AccountDetails/AccountOverview/index.js [hunk 1]
```diff
@@ -55,9 +55,9 @@ export default function AccountOverview() {
         </BoxHeader>
         <BoxContent className={styles.content}>
           {activeTab === 'transactions' ? (
-            <Transactions address={currentAddress} />
+            <Transactions address={searchAddress ?? currentAddress} />
           ) : (
-            <TransactionEvents isWallet hasFilter address={currentAddress} />
+            <TransactionEvents isWallet hasFilter address={searchAddress ?? currentAddress} />
```
Comment (eniolam1000752) [inline src/modules/account/components/AccountDetails/AccountOverview/index.js]: instead of having `searchAddress ?? currentAddress` in multiple places I think you can define it in a variable on top and reuse that variable

`const address = searchAddress ?? currentAddress`

File: src/modules/search/components/SearchBar/SearchBar.js [hunk 2]
```diff
@@ -67,8 +67,8 @@ const SearchBar = ({ className }) => {
   const onSelectBlock = (value) => onSelectedRow('block', value);
 
   const onKeyPress = () => {
-    if (addresses.length) {
-      onSelectAccount(addresses[rowItemIndex].address);
+    if (Object.keys(addresses).length) {
+      onSelectAccount(addresses.address);
     }
```
Comment (eniolam1000752) [inline src/modules/search/components/SearchBar/SearchBar.js:72]: instead of this I think you can assert by this

```suggestion
    if (addresses.address) onSelectAccount(addresses.address)
```

File: src/modules/wallet/components/searchBarWallets/index.js [hunk 3]
```diff
@@ -3,52 +3,46 @@ import WalletVisual from '@wallet/components/walletVisual';
...
+              <span className={`${styles.accountTitle} account-title`}>{wallet.address}</span>
+            )}
           </div>
-        ))}
+          <span className={styles.accountBalance}>
+            {isValidator ? (
+              <span className={`${styles.tag} tag`}>
+                {wallet.rank ? t('Validator #{{rank}}', { rank: wallet.rank }) : '-'}
+              </span>
+            ) : null}
```
Comment (eniolam1000752) [inline src/modules/wallet/components/searchBarWallets/index.js]:
```suggestion
            {isValidator && (
              <span className={`${styles.tag} tag`}>
                {wallet.rank ? t('Validator #{{rank}}', { rank: wallet.rank }) : '-'}
              </span>
            )}
```

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]

File: src/modules/account/components/AccountDetails/AccountOverview/index.js (hunk 1 above)
Comment (ikem-legend) [reply src/modules/account/components/AccountDetails/AccountOverview/index.js]: Fixed

File: src/modules/wallet/components/searchBarWallets/index.js (hunk 3 above)
Comment (ikem-legend) [reply src/modules/wallet/components/searchBarWallets/index.js]: Fixed

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]
UI/UX concerns

- Ui look weird
image

- Searching for non validator account on the global search only works on for exact search

File: src/modules/search/components/SearchBar/SearchBar.js (hunk 2 above)
Comment (ikem-legend) [reply src/modules/search/components/SearchBar/SearchBar.js:72]: This was done for consistency with the other conditions in the function

**Comment by ikem-legend** [comment]
> UI/UX concerns
> 
> * Ui look weird
> 
> image
> * Searching for non validator account on the global search only works on for exact search

To be fixed in #5077

**Review by ManuGowda — CHANGES_REQUESTED** [review]
Screenshot 2023-06-12 at 10 01 44 AM

File: src/modules/account/components/AccountDetails/AccountOverview/index.js [hunk 4]
```diff
@@ -40,6 +40,7 @@ export default function AccountOverview() {
     active: activeTab,
     onClick: ({ value }) => setActiveTab(value),
   };
+  const userAddress = searchAddress ?? currentAddress;
```
Comment (ManuGowda) [inline src/modules/account/components/AccountDetails/AccountOverview/index.js]: we never try to use term `user`, lets rename to `accountAddress` or just `address`?

**Review by ManuGowda — CHANGES_REQUESTED** [review]

File: src/modules/account/components/AccountDetails/AccountOverview/index.js (hunk 4 above)
Comment (ikem-legend) [reply src/modules/account/components/AccountDetails/AccountOverview/index.js]: Fixed

**Review by ManuGowda — DISMISSED** [review]

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]
## Ui/UX issue observed

- I tried to send some tokens to an account via the explore page. I was successfully able to send tokens but clicking the add to bookmark breaks the application.

**Comment by ikem-legend** [comment]
> ## Ui/UX issue observed
> * I tried to send some tokens to an account via the explore page. I was successfully able to send tokens but clicking the add to bookmark breaks the application.

Fixed

**Review by ManuGowda — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
