### PR TITLE
Fix general UI issues

### LINKED ISSUE #4903: General UI and settings issues on alpha.1
### Expected behavior
- The texts needs to reviewed and updated overall and also we need to check the grammar, examples
   - Not empty => Non empty
   - All applications => Explore applications
   - Select network => Switch network
   - Select application => Switch application

- Integrate market prices
**Service endpoint:** http://devnet-service.liskdev.net:9901/api/v3/market/prices
We also need to implement in widget, here is the [design](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?node-id=38-12157&t=ImwAR7OLNAbUehKd-4)

   - For unknown pairing i.e EVT_EUR use `-` or for any unknown pairing in general
   - For wallet home page, if pairing doesn’t exists don’t show
image

- Tool tip on application explore statistics should not have lots of spaces
image

- Add copy option for publickey, currently we are missing the option
image

- Refactor modal UI to be consistent  with other implementations like we have it in the send token flow
image

- Replace `Back` button functionality with `Close` on the sign message functionality. Close here means that the modal should be dismissed when clicked.
image

### Which version(s) does this affect? (Environment, OS, etc...)
- All versions

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4903

### How was it solved?

- [x] Fixed dark mode on json viewer
- [x] Added ability to copy public key on `WalletVisualWithAddress` component
- [x] Fixed enter password step on sign message
- [x] Refactored back button on the final step of sign message 
- [x] Implemented and consumed useFiatRate hook on TokenCard and AllToken table
- [x] Updated text
- [x] Fixed tooltip on application statistics page
- [x] Fix failing unit tests

### How was it tested?

- Jest
- Visually

### CODE REVIEW

**Review by ManuGowda — COMMENTED** [review]
bugs found

1. All tokens back button leads to wrong page. Steps to reproduce, clock on view all tokens, click on settings change currency, close settings modal, clock on back button next to `all tokens` 
2. Text update needed
Screenshot 2023-04-17 at 7 09 53 PM

**Review by ManuGowda — DISMISSED** [review]

File: src/modules/wallet/components/walletVisualWithAddress/index.js [hunk 1]
```diff
@@ -98,21 +100,40 @@ const WalletVisualWithAddress = ({
...
+                  truncatedAddress={truncatedAddress}
+                  name={accountName}
+                  isMultisig={isMultisig}
+                />
+              </div>
+            </div>
+          }
+        >
+          <div className={styles.pubkey}>
+            <span>Publick key:</span>
```
Comment (ikem-legend) [inline src/modules/wallet/components/walletVisualWithAddress/index.js]: Typo in `Publick`

File: src/modules/common/hooks/useFiatRates.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+export default function useFiatRates() {
+  const marketPrice = useMarketPrices();
+
+  return useMemo(() => {
+    const marketPrices = marketPrice.data?.data || [];
+    return marketPrices.reduce(
+      (result, { from, to, rate }) => ({ ...result, [from]: { ...result[from], [to]: rate } }),
+      {}
+    );
+  }, [marketPrice.isFetching, marketPrice.isFetched, marketPrice.isError, marketPrice.data]);
```
Comment (ikem-legend) [inline src/modules/common/hooks/useFiatRates.js]: Are both `isFetching` and `isFetched` necessary in the dependency array?

File: src/modules/message/components/signedMessage/index.js [hunk 3]
```diff
@@ -1,40 +1,42 @@
...
   <>
-    <BoxContent className={styles.noPadding}>
+    <BoxContent>
       <AutoResizeTextarea className={`${styles.result} result`} value={signature} readOnly />
     </BoxContent>
     <BoxFooter direction="horizontal">
       <SecondaryButton
         onClick={() => {
+          removeSearchParamsFromUrl(history, ['modal'], true);
           onPrev?.();
```
Comment (ikem-legend) [inline src/modules/message/components/signedMessage/index.js]: Line 35 should come before line 34 to prevent trying to modify a state after a component has been unmounted

**Review by ikem-legend — COMMENTED** [review]
LGTM. Just some minor changes left

**Review by ikem-legend — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
