### PR TITLE
Fix custom derivation path

### LINKED ISSUE #4591: Default custom derivation path setting is overridden
### Expected behavior

When a user adds new account the default custom derivation path should be `m/44'/134'/0'`

### Actual behavior

Default custom derivation path setting is overridden
Screenshot 2022-11-23 at 11 59 04 AM

### Steps to reproduce

- Enable custom derivation path in `settings`
- Add an account
- Change default path to `m/44'/134'/5'`
- After the successful account addition, add another account
- Observe the default derivation path is set to `m/44'/134'/5'` instead of `m/44'/134'/0'`

### Which version(s) does this affect? (Environment, OS, etc...)
v3

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #4591 #4616

### How was it solved?

- Remove custom derivation path from redux 
- Add validation to derivation path, typing an incorrect derivation path shall prevent a user to go to SetPasswordForm
- Fix alignment bug of error icon when input size = m

### How was it tested?

Manually

### CODE REVIEW

File: src/modules/account/components/AddAccountForm/AddAccountForm.js [hunk 1]
```diff
@@ -22,18 +23,42 @@ const AddAccountForm = ({ settings, onAddAccount }) => {
...
+  children,
+}) => {
+  const { t } = useTranslation();
+
   const onFormSubmit = (e) => {
     e.preventDefault();
     // istanbul ignore else
     if (passphrase.value && passphrase.isValid) {
-      onAddAccount(passphrase);
+      onAddAccount(passphrase, derivationPath);
```
Comment (ManuGowda) [inline src/modules/account/components/AddAccountForm/AddAccountForm.js:49]: Now that you separated the logic, I am not sure why do we need to pass this property? an account can be created with or without derivationPath.
- With derivationPath: either default or specific
- Without derivationPath: nothing to pass

File: src/modules/wallet/utils/account.js [hunk 2]
```diff
@@ -303,3 +304,48 @@ export const validate2ndPass = async (account, passphrase, error) => {
   }
   return messages;
 };
+
+/**
+ * Validate a derivation path
+ * TODO: Replace this function when @liskhq (lisk-sdk) exposes the one they use
```
Comment (ManuGowda) [inline src/modules/wallet/utils/account.js]: could you please GitHub issue in SDK repo and link the issue here?

File: src/modules/account/components/AddAccountForm/AddAccountForm.js (hunk 1 above)
Comment (oskarleonard) [reply src/modules/account/components/AddAccountForm/AddAccountForm.js:49]: The `AddAccountForm` handle both those states so for one state `derivationPath` is return and for the other state `derivationPath` is not returned.

File: src/modules/wallet/utils/account.js (hunk 2 above)
Comment (oskarleonard) [reply src/modules/wallet/utils/account.js]: Do you mean that we shall wait to merge this until response from SDK?

https://github.com/LiskHQ/lisk-sdk/issues/7877

File: src/theme/buttons/css/base.css [hunk 3]
```diff
@@ -65,6 +65,7 @@
 
   &:disabled {
     opacity: 0.58;
+    cursor: default;
```
Comment (clemente-xyz) [inline src/theme/buttons/css/base.css:68]:
```suggestion
    cursor: not-allowed;
```

**Review by clemente-xyz — CHANGES_REQUESTED** [review]
small obs

File: src/theme/buttons/css/base.css (hunk 3 above)
Comment (oskarleonard) [reply src/theme/buttons/css/base.css:68]: I thought of that one but `cursor: default;` seems to be the current state for disabled buttons when i searched through the codebase, I didn't want to break any current design patterns (I have worked with designers that think `not-allowed` just adds confusion). Many "go to" design systems dont use it either and it is not even used here on github. 

Personally, as a user it would just add confusion to me because barely no other site is using it for disabled states.

File: src/modules/wallet/utils/account.js (hunk 2 above)
Comment (ManuGowda) [reply src/modules/wallet/utils/account.js]: No we dont need to wait, in line 310 TODO we can refer the above SDK issue and we can clean this up once SDK exposes the function

**Review by ManuGowda — APPROVED** [review]

File: src/modules/wallet/utils/account.js (hunk 2 above)
Comment (oskarleonard) [reply src/modules/wallet/utils/account.js]: Done

File: src/theme/buttons/css/base.css (hunk 3 above)
Comment (clemente-xyz) [reply src/theme/buttons/css/base.css:68]: Hmm i don't agree with you at all :)

I think we should make use as much as possible of cursor state-changes resources — is a very important accessibility aid for users, specially the ones using keyboard controls.

That Github or other websites don't use them does not mean they are right :)

[MDN](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/CSS_and_JavaScript) explains good the point I'm addressing on this comment.

Comment (oskarleonard) [reply src/theme/buttons/css/base.css:68]: I am fine with using it as long as it is consistent throughout the application. I have created an issue regarding this https://github.com/LiskHQ/lisk-desktop/issues/4664

**Review by clemente-xyz — APPROVED** [review]
Approving considering that it will be addressed on https://github.com/LiskHQ/lisk-desktop/issues/4664
