### PR TITLE
Checkbox should not look like radio button

### LINKED ISSUE #4590: Checkbox is rendered as radio button
### Expected behavior

- Checkbox should be rendered as checkbox and not appear like radio button

Screenshot 2022-11-23 at 11 47 43 AM

### Actual behavior

Screenshot 2022-11-23 at 11 47 53 AM

### Steps to reproduce

- Access application feature where we have checkbox options (settings, add account flow, etc..)

### Which version(s) does this affect? (Environment, OS, etc...)
v3

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #4590

### How was it solved?

- By lessening border radius on the checkbox
- By removing the warning "A component is changing an uncontrolled input to be controlled" in the checkbox as well as the SetPasswordForm.

### How was it tested?

Manually

### CODE REVIEW

**Review by ManuGowda — DISMISSED** [review]
LGTM

File: src/modules/auth/components/SetPasswordForm/SetPasswordForm.js [hunk 1]
```diff
@@ -76,23 +77,18 @@ function SetPasswordForm({ onSubmit, recoveryPhrase }) {
             secureTextEntry
             feedback={errors.password?.message}
             status={errors.password ? 'error' : undefined}
-            defaultValues=""
-            value={password}
-            label={(
-              <span className="password-label-wrapper">
+            label={
+              <span className="password-label-wrappe ">
```
Comment (ikem-legend) [inline src/modules/auth/components/SetPasswordForm/SetPasswordForm.js]: @oskarleonard I believe this was meant to be `password-label-wrapper`

Comment (oskarleonard) [reply src/modules/auth/components/SetPasswordForm/SetPasswordForm.js]: Should be fixed now, great catch

**Review by ikem-legend — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
