### PR TITLE
Connection status Lisk logo

### LINKED ISSUE #5186: ConnectionStatus modal for wallet connect should show app logo
### Expected behavior
Use wallet connect app logo or walletConnectFallback logo in `ConnectionStatus.js`

### Actual behavior
liskLogo is hardcoded in `ConnectionStatus.js`

### Steps to reproduce
Connect an account to wallet connect check the confirmation success modal `ConnectionStatus.js` .

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5186

### How was it solved?

Pass ConnectionStatus the icon and use walletConnect as default

### How was it tested?

Last connection confirmation modal when connecting to WC should show WC icon or the icon being passed from WC

### CODE REVIEW

File: src/modules/blockchainApplication/explore/components/BlockchainAppDetailsHeader/index.js [hunk 1]
```diff
@@ -22,6 +22,7 @@ const BlockchainAppDetailsHeader = ({
 }) => {
   const { t } = useTranslation();
   const { name, projectPage, icon } = application.data;
+  console.log('icon', icon);
```
Comment (ikem-legend) [inline src/modules/blockchainApplication/explore/components/BlockchainAppDetailsHeader/index.js]: Please remove console log

**Review by ikem-legend — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
