### PR TITLE
Fix blockchain apps display issue

### LINKED ISSUE #5564: Blockchain apps displayed incorrectly
### Expected behavior
Blockchain apps should be correctly displayed with no duplicates.

### Actual behavior
There's an issue with correctly displaying blockchain apps where an app shows up as duplicate .
Screenshot 2024-01-02 at 10 57 39

### Steps to reproduce
- Open the blockchain apps page
- View the list of apps

### Which version(s) does this affect? (Environment, OS, etc...)
All

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #5564

### How was it solved?

- Updating the apps merging logic
- Implemented removing flash message when opening blockchain app details

### How was it tested?

- Manually

### CODE REVIEW

**Review by oskarleonard — APPROVED** [review]

**Review by Balanced02 — APPROVED** [review]

File: src/modules/blockchainApplication/manage/hooks/useMergeApplicationExploreAndMetaData.js [hunk 1]
```diff
@@ -12,15 +12,33 @@ const useMergeApplicationExploreAndMetaData = (appOnChainData = [], isUnion = fa
...
+      );
 
-  if (!isUnion) {
-    filteredOnChainData = filteredOnChainData.filter(({ chainID }) =>
-      appMetaData.some(({ chainID: metaDataChainId }) => metaDataChainId === chainID)
-    );
-  }
+  return isLoading
+    ? filteredOnChainData
+    : (() => {
```
Comment (Balanced02) [inline src/modules/blockchainApplication/manage/hooks/useMergeApplicationExploreAndMetaData.js]: ...why not extract this to a named function for clarity

Comment (ikem-legend) [reply src/modules/blockchainApplication/manage/hooks/useMergeApplicationExploreAndMetaData.js]: Done

**Review by Balanced02 — APPROVED** [review]

**Review by oskarleonard — APPROVED** [review]
