### PR TITLE
The delegate registration timeline graph is blank - Closes #3507

### LINKED ISSUE #3507: The delegate registration timeline graph is blank
### Expected behavior
The graph should display distribution of delegate registrations over time. 

### Actual behavior
The graph doesn't render.

### Steps to reproduce
Navigate to the delegates page.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-alpha.6

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?
This PR resolves #3507

### How was it solved?
- Removed all response transformations and nomalized response in API level.
- Shortened parameter names for better readability.
- Noticed the total transactions count was hard coded and fixed it.

### How was it tested?
Unit tests

### CODE REVIEW

File: src/utils/api/transaction/lsk.js [hunk 1]
```diff
@@ -127,33 +127,47 @@ export const getRegisteredDelegates = async ({ network }) => {
...
+      } else if (acc[0][0] === null) {
+        acc[0][0] = month;
+        acc.unshift([null, acc[0][1] - monthStats[month]]);
+      }
+
+      return acc;
+    }, [[getDate(txs.data[0].block.timestamp), delegates.meta.total]]);
+
+  // Add the date of one month before the last tx
+  res[0][0] = getDate(txs.data[txs.data.length - 1].block.timestamp - 2678400);
```
Comment (isalga) [inline src/utils/api/transaction/lsk.js:168]: Why this `- 2678400` ?

Comment (reyraa) [reply src/utils/api/transaction/lsk.js:168]: This is the timestamp value of 1 month.

**Review by UsamaHameed — APPROVED** [review]

**Review by isalga — APPROVED** [review]
