### PR TITLE
Fix race condition between account updated action and initialization transaction

### LINKED ISSUE #3393: Fix race condition between account initialization transaction and account updated api call
### Expected behavior
The user should not see the intialization transaction screen after having submitted the initialization transaction. 

### Actual behavior
The user sees the initialization transaction after having broadcasted the transaction.

### PR DESCRIPTION
**Pull request by UsamaHameed**
### What was the problem?
This PR resolves #3393

### How was it solved?
By executing the account init logic after the account updated action

### How was it tested?
Manually and unit tests

### CODE REVIEW

File: src/store/middlewares/account.js [hunk 1]
```diff
@@ -239,6 +247,11 @@ const accountMiddleware = store => next => (action) => {
     case actionTypes.updateTransactions:
       votePlaced(store, action);
       break;
+    case actionTypes.accountUpdated:
```
Comment (isalga) [inline src/store/middlewares/account.js:250]: If this case is empty then it should be removed to it goes to `default: break;`

**Review by isalga — CHANGES_REQUESTED** [review]

File: src/store/middlewares/account.js (hunk 1 above)
Comment (UsamaHameed) [reply src/store/middlewares/account.js:250]: This case is not empty. I have combined two cases together because the function to use in both the cases is the same.

**Review by isalga — APPROVED** [review]
