### PR TITLE
Fixed bugs identified in staking and un-staking validators

### LINKED ISSUE #4896: Bugs identified in staking and un-staking validators
### Expected behavior

- Users should be able to stake a validator
- Show valid token summary after successfully staking validators
- Rewards should be claimable if its above 0 tokens

### Actual behavior

- Unable to stake a validator
- Invalid token summary after successfully staking validators
- Invalid claimable rewards calculation

### Steps to reproduce

- Unable to stake a validator
  - Try to stake a validator 
- Invalid token summary after successfully staking validators
  - Stake more than 1 validator to see the summary of tokens in `staking success` view 
- Invalid claimable rewards calculation
  - Rewards button is activated when they have 0 rewards to claim
 
### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #4896

### How was it solved?

- Fixed the destructing issue to view the balance thus enabling to stake a validator
- Fixed the reduced to accumulate stakes based on BigInt for a successfully staking validators
- Fixed the claimable rewards logic

### How was it tested?

- Verified all the bugs manually

### CODE REVIEW

File: src/modules/token/fungible/hooks/queries/useTokenBalances.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const useTokenBalances = ({
   client = defaultClient,
 } = {}) => {
   const [currentAccount] = useCurrentAccount();
-  const { address } = customConfig.params?.address || currentAccount.metadata || {};
+  const address = customConfig.params?.address || currentAccount.metadata?.address;
```
Comment (oskarleonard) [inline src/modules/token/fungible/hooks/queries/useTokenBalances.js:24]: Nice! This will also fix register as a validator! 👍 and probably some other bugs as well 🎉

**Review by oskarleonard — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
