### PR TITLE
Resolve transactions event update issue

### LINKED ISSUE #4930: Transaction list does get updated after a transaction
### Expected behavior
- After a transaction is done, transaction list on wallet should update showing new transaction recrod

### Actual behavior
- Transactions table on the wallet page does not get updated

### Steps to reproduce
- Perform a transaction
- Navigate to the wallet page
- Transaction table does not get updated.

### Which version(s) does this affect? (Environment, OS, etc...)
- 3.0.0

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4930

### How was it solved?

- [x] Added client.socket dependency to useEffect on useTransctionUpdate

### How was it tested?

- Visually
- Jest

### CODE REVIEW

File: src/utils/api/client.js [hunk 1]
```diff
@@ -49,6 +49,7 @@ export class Client {
 
   create({ ws, http } = {}) {
     if (ws) {
+      console.log('===', `${ws}/blockchain`);
```
Comment (ikem-legend) [inline src/utils/api/client.js]: @eniolam1000752 Please remove this log

File: setup/react/app/ApplicationBootstrap.js [hunk 2]
```diff
@@ -48,6 +47,8 @@ const ApplicationBootstrap = ({ children }) => {
     (networkStatus.isLoading && !!mainChainNetwork) ||
     (blockchainAppsMeta.isLoading && !!mainChainApplication);
 
+  useTransactionUpdate();
```
Comment (oskarleonard) [inline setup/react/app/ApplicationBootstrap.js]: Why did we move this one? Feels cleaner if all hooks are at the same place if they arent dependent on some variable, and we dont seem to pass in `mainChainApplication`, `isError`, nor `isLoading` to this hook

**Review by oskarleonard — DISMISSED** [review]

**Review by ikem-legend — DISMISSED** [review]

**Review by ManuGowda — CHANGES_REQUESTED** [review]
On sending tokens i see duplicate rows for same information

Screenshot 2023-04-21 at 5 14 16 PM


It should show only one row

**Review by ManuGowda — APPROVED** [review]

**Review by oskarleonard — APPROVED** [review]
