### PR TITLE
Fixed ban details display bug with performance details modal

### LINKED ISSUE #3913: App crashes while trying to view ban details of banned delegate
### Expected behavior
The modal for the delegate ban details including start and end height should be displayed properly when the details button is clicked while viewing performance status of banned delegate

### Actual behavior
App crashes when the details button is clicked to see ban details 

### Steps to reproduce
1. Open the delegates page
2. Select sanctioned tab
3. Select a banned delegate
4. Click the delegate profile section of the banned delegate
5. Click the details button under the status widget in the Performance section

### Which version(s) does this affect? (Environment, OS, etc...)
Windows, OS 10

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #3913

### How was it solved?

It was solved by conditionally displaying ban/punishment details based on status

### How was it tested?

Visually

### CODE REVIEW

File: src/components/screens/wallet/delegatePerformance/delegatePerformance.js [hunk 1]
```diff
@@ -33,28 +33,34 @@ const DelegatePerformance = ({ delegate: { error, isLoading, data } } = {}) => {
         <Box className={grid.row}>
           <Box className={`${grid['col-md-12']} ${grid['col-xs-12']}`}>
             <p className={styles.description}>
-              {delegatePerformanceDetails(pomHeights.length, status, consecutiveMissedBlocks)}
+              {pomHeights?.length
+                ? delegatePerformanceDetails(pomHeights.length, status, consecutiveMissedBlocks)
+                : 'The delegate was banned after 5 punishments.'}
```
Comment (ManuGowda) [inline src/components/screens/wallet/delegatePerformance/delegatePerformance.js:38]: since status `The delegate is permanently banned from generating blocks due to repeated protocol violations or missing too many blocks.` itself is very much clear and we do not have details to show. We can remove the details link and keep just the status?

Comment (ikem-legend) [reply src/components/screens/wallet/delegatePerformance/delegatePerformance.js:38]: @ManuGowda Resolved

**Review by ManuGowda — APPROVED** [review]

**Review by ManuGowda — COMMENTED** [review]
🤔 the pomHeight null check is removed?

**Review by reyraa — APPROVED** [review]

**Comment by ikem-legend** [comment]
> 🤔 the pomHeight null check is removed?

Yes, it's handled in the `delegatePerformanceDetails` function and while displaying the details (`pomHeights && pomHeights.map...`) on the page

**Comment by ikem-legend** [comment]
> > 🤔 the pomHeight null check is removed?
> 
> @ManuGowda Yes, it's handled in the `delegatePerformanceDetails` function and while displaying the details (`pomHeights && pomHeights.map...`) on the page
