### PR TITLE
Fix low impact issues from DeepScan - Closes #2794

### LINKED ISSUE #2794: Fix low impact issues from DeepScan
## Current situation
DeepScan reports over 40 low impact issues https://deepscan.io/dashboard/#view=project&tid=6759&pid=8871&bid=113511&subview=overview

## Expected situation
All DeepScan low impact issues should be fixed or marked as irrelevant with an explanation

### PR DESCRIPTION
**Pull request by slaweet**
### What was the problem?
This PR resolves #2794

### How was it solved?

Resolved issues one by one. For each issue there is one of these two options:
- this PR contains a commit with commit message linking to the issue and the issue is marked as "Confirmed" inside DeepScan
- the issue is marked as "Won't fix" or "False positive" inside DeepScan and commented with an explanation

https://deepscan.io/dashboard/#view=project&tid=6759&pid=8871&bid=113511&subview=issues&impact=%5B%22Low%22%5D&page=1&status=%5B%22open%22%2C%22confirmed%22%2C%22wont-fix%22%2C%22false-positive%22%2C%22fixed%22%5D&orderBy=FilePath&orderType=-

### How was it tested?

Check that tests still pass and there are no regressions.

### CODE REVIEW

File: src/components/shared/converter/converter.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ class Converter extends React.Component {
       ? 0
       : (numeral(value).value() * currencies[currency]);
 
-    price = price > converter.maxLSKSupply || price === 'NaN' || price < 0 ? 0 : price;
```
Comment (reyraa) [inline src/components/shared/converter/converter.js]: How did this work in the past? :-D

File: src/utils/getNetwork.js [hunk 2]
```diff
@@ -42,16 +42,13 @@ export const getNetworksList = () =>
...
-    activeNetwork = network.networks[token].nethash === Lisk.constants.MAINNET_NETHASH
-      ? networks.mainnet.name
-      : network.name;
     activeNetwork = network.networks[token].nethash === Lisk.constants.TESTNET_NETHASH
       ? networks.testnet.name
       : network.name;
   }
 
   if (network.name === networks.customNode.name && token === 'BTC') {
-    activeNetwork = token === 'BTC' ? networks.testnet.name : network.name;
```
Comment (reyraa) [inline src/utils/getNetwork.js]: Why did you remove this? it was quite a fun!
