### PR TITLE
Delagate vote transaction details displays 0 as amount of transaction - Closes #3318

### LINKED ISSUE #3318: Delagate vote transaction details displays 0 as amount of transaction
### Expected behavior
Should display the total amount of the vote transaction

### Actual behavior
Display 0 on transaction details and '-' on transaction list

### Steps to reproduce
- Vote for a delegate
- Go to wallet transaction list and transaction details

### Which version(s) does this affect? (Environment, OS, etc...)
macOs, feature-forging-delegates

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?
This PR resolves #3318

### How was it solved?
Hid tx amount for types other than transfer

### How was it tested?
Unit tests

### CODE REVIEW

**Review by UsamaHameed — APPROVED** [review]

File: src/components/screens/transactionDetails/dataRows.js [hunk 1]
```diff
@@ -133,16 +105,21 @@ export const AmountAndDate = ({
...
-        <span className={styles.label}>
-          {t('Amount of Transaction')}
-        </span>
-        <DiscreetMode addresses={addresses} shouldEvaluateForOtherAccounts>
-          <span className="tx-amount">
-            <LiskAmount val={getTxAmount(transaction)} token={activeToken} />
-          </span>
-        </DiscreetMode>
-      </div>
+      { transaction.title === 'transfer' || transaction.title === 'unlockToken'
```
Comment (isalga) [inline src/components/screens/transactionDetails/dataRows.js:108]:
```suggestion
{ transaction.type === transactionTypes().transfer.code.new
|| transaction.type === transactionTypes().unlockToken.code.new
```

**Review by isalga — CHANGES_REQUESTED** [review]

**Review by isalga — APPROVED** [review]
