### PR TITLE
Display sign and verify message menu items only for LSK - Closes #2699

### LINKED ISSUE #2699: Sign and verify message - BTC Wallet
### Expected behavior

As of you are not able to sign or verify a message for BTC, you shouldn't see those actions.

### Actual behavior

The user currently sees the actions, when he switches from the Lisk to BTC wallet.

Screenshot 2019-12-11 at 10 52 52

### Steps to reproduce

Dashboard -> Open the dropdown on the top right corner -> Select BTC -> reopen the dropdown

### Which version(s) does this affect? (Environment, OS, etc...)

1.23.0

### PR DESCRIPTION
**Pull request by reyraa**
### What issue have I solved?

Resolves #2699 

### How have I implemented/fixed it?
As requested, I show the sign message and verify message menu items only when LSK is active.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/shared/header/topBar/accountMenu/userAccount.js [hunk 1]
```diff
@@ -66,127 +101,86 @@ class UserAccount extends React.Component {
...
-              >
-                <Icon name="sign" className={styles.defaultIcon} />
-                <Icon name="signActive" className={styles.activeIcon} />
-                <span>{t('Sign Message')}</span>
-              </Link>
+              />
+            ) : null
+        }
+        {
+          token.active !== 'BTC'
```
Comment (slaweet) [inline src/components/shared/header/topBar/accountMenu/userAccount.js]: It is already defined that this page is forbidden for BTC in https://github.com/LiskHQ/lisk-desktop/blob/e7fefb9dc3bd310617a339a69200c264b946db7e/src/constants/routes.js#L108

💡 IMO it would be DRYer re-use `forbiddenTokens` here:

```suggestion
          !routes.verifyMMessage.forbiddenTokens.includes(token.active)
```

Comment (reyraa) [reply src/components/shared/header/topBar/accountMenu/userAccount.js]: Thanks Vit. This looks pretty verbose and less readable. plus, you have to open another file to see where is this coming from and such. I rather keep my own if you mind.

Comment (slaweet) [reply src/components/shared/header/topBar/accountMenu/userAccount.js]: Sure 👍
