### PR TITLE
Bug fix transaction details, staking and transaction filtering

### LINKED ISSUE #5436: Add transaction value to transaction details
### Description

Currently we only show the transaction value in table row and not in details. Add transaction value that is present in row to transaction details for consistency.

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5436,  #5435, #5439 and #5434

### How was it solved?

- [x] Filter out non-recognised transaction types on transaction list filter 
- [x] Add value to transaction details page
- [x] Continuous multi sig flow staking transaction. Silently switch to next account, prevent the "Are you sure?" switch. 

### How was it tested?

Transaction filter by types
1. Switch to a side chain
2. Navigate to the wallet or transaction monitor page
3. Try to filter the transaction by transaction type.
4. I should be observed that there are no missing transaction types in the Transaction type filter options.

Continuous flow for multi sig staking
1. Try to stake with a multi sig wallet (you should have the other required wallet in your accounts)
5. Continue to switch to required wallet and sign the transaction
6. Expected: Should work.

### CODE REVIEW

**Review by ikem-legend — DISMISSED** [review]

**Review by eniolam1000752 — DISMISSED** [review]

File: src/modules/blockchainApplication/explore/components/BlockchainApplicationDetails/BlockchainApplicationDetails.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ const BlockchainApplicationDetails = ({ history, location }) => {
     lastCertificateHeight,
     lastUpdated,
     logo,
-    depositedLsk = 0,
+    escrowedLSK = '0',
```
Comment (ikem-legend) [inline src/modules/blockchainApplication/explore/components/BlockchainApplicationDetails/BlockchainApplicationDetails.js:53]: NRTTL this change needs to be replicated for blockchain application view and remove blockchain application as well as some test and fixture files

**Review by ikem-legend — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
