### PR TITLE
Validator's name shouldn't appear on the wallet page

### LINKED ISSUE #5126: Validator's name shouldn't appear on the wallet page
### Expected behavior

My validator name shouldn't be appearing on my wallet page. it should only appear as part of the validator details in "my validator profile" page.

### Actual behavior

When I create a validator account, the name I use is appearing on my wallet page as my account name even if I have a different name as the account name.
Screenshot 2023-06-29 at 10 33 38

### Steps to reproduce

Follow the proposed design on the validator's design. (https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=38%3A46919&mode=design&t=GGXmxLLCWV0x6EHL-1)

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5126

### How was it solved?

- Remove use of validator name on account page
- Show validator name on my validator profile

### How was it tested?

1. Go to http://0.0.0.0:8080/#/wallet with a validator account 
2. Expected: Account name should be shown and not validator name
3. Go to http://0.0.0.0:8080/#/validators/profile?address=lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad with a validator account 
4. Expected: Show validator name in the details section

### CODE REVIEW

**Review by ikem-legend — DISMISSED** [review]

File: src/modules/wallet/components/overview/overview.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ const Overview = ({ isWalletRoute, history }) => {
           copy
           size={50}
           address={authData?.meta?.address}
-          accountName={searchAddress || validator.name ? validator.name : name}
```
Comment (ManuGowda) [inline src/modules/wallet/components/overview/overview.js:107]: You have to leave this as it was, when we search for a validator, in the wallet page it should show the searched validator name.

Actual

Screenshot 2023-07-31 at 10 54 39 PM


Expected

Screenshot 2023-07-31 at 10 54 21 PM

Comment (oskarleonard) [reply src/modules/wallet/components/overview/overview.js:107]: Hmm, I dont think we can leave as it was? Whole ticket was about not showing the validator name for current account. 

Made some modifications here that should account for the state in this conversation, please check:

https://github.com/LiskHQ/lisk-desktop/pull/5213/commits/4c8c977962cc8d14f4c53adbe3dac8088996d89e

**Review by ikem-legend — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
