### PR TITLE
Continuous flow for multisig transaction signing

### LINKED ISSUE #5340: Transaction signing regression
### Expected behavior
Being given the ability to immediately sign a transaction with a second multisig passphrase, just like in the current version (v2.3.0).

### Actual behavior
A window is shown to download the transaction, without an option to sign it with another passphrase instead.

### Steps to reproduce
1. Create a transaction
2. Sign it with your password

### Which version(s) does this affect? (Environment, OS, etc...)
Version 3.0.0-rc.1

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5340

### How was it solved?

Added logic to continue multi sig flow if required accounts exists in users wallet management. 

#### Case 1 - 3 mandatory accounts in account management
1. Create a multi sig account with 3 mandatory accounts (that exists in your account management)
2. Initiate a send transaction from account 1
3. Expected: you should be able to continue the signing flow and when the last accounts signs it should be given the option to send the transaction

#### Case 2 - Two Mandatory 1 optional
1. Create a multi sig account with 2 mandatory and 1 optional accounts (all exists in your account management)
2. Initiate a send transaction from account 1
3. Expected: you should be able to continue the signing flow and when the last accounts signs it should be given the option to send the transaction

#### Case 3 - Two Mandatory (one doesnt exists in your account management)
1. Create a multi sig account with 2 mandatory accounts (One of them should not exist in your account management)
2. Initiate a send transaction from account 1
3. Expected: you should now be given the option to continue signing (since next wallet doesnt exists in your account manangement)

#### Case 4 - Edit a multisig account
1. Try editing a required account for a multi sig account
2. Expected: you should now be given the option to continue signing for all the accounts and in the end be presented with a send transaction which should change the multisig account.

### CODE REVIEW

File: src/modules/transaction/components/Multisignature/Multisignature.js [hunk 1]
```diff
@@ -7,20 +7,63 @@ import { txStatusTypes } from '@transaction/configuration/txStatus';
 import { getErrorReportMailto } from 'src/utils/helpers';
 
 import copyToClipboard from 'copy-to-clipboard';
-import { toTransactionJSON, downloadJSON, joinModuleAndCommand } from '@transaction/utils';
+import { downloadJSON, joinModuleAndCommand, toTransactionJSON } from '@transaction/utils';
 import { MODULE_COMMANDS_NAME_MAP } from '@transaction/configuration/moduleCommand';
 import Icon from 'src/theme/Icon';
+import { useAccounts, useCurrentAccount } from '@account/hooks';
+import { calculateRemainingAndSignedMembers, truncateAddress } from '@wallet/utils/account';
+import { ReactComponent as SwtichIcon } from '@setup/react/assets/images/icons/switch-icon.svg';
```
Comment (ikem-legend) [inline src/modules/transaction/components/Multisignature/Multisignature.js]: Typo in `SwtichIcon`

File: src/modules/wallet/components/signMultisigView/index.js [hunk 2]
```diff
@@ -5,23 +5,42 @@ import { removeSearchParamsFromUrl } from 'src/utils/searchParams';
...
+import { useSchemas } from '@transaction/hooks/queries/useSchemas';
+import { useDeprecatedAccount } from '@account/hooks';
+import { joinModuleAndCommand } from '@transaction/utils';
 import Form from '../signMultisigForm';
 import Summary from '../signMultisigSummary';
 import Status from '../signMultisigStatus';
 
 const SignMultisigView = ({ history }) => {
-  const [isStepTxSignatureCollector, setIsStepTxSignatureCollector] = useState(false);
+  const [currentStep, setIsStepTxSignatureCollector] = useState();
```
Comment (ikem-legend) [inline src/modules/wallet/components/signMultisigView/index.js]: Since the getter was renamed, shouldn't the setter be renamed accordingly?

File: src/modules/transaction/components/Multisignature/Multisignature.js (hunk 1 above)
Comment (oskarleonard) [reply src/modules/transaction/components/Multisignature/Multisignature.js]: Nice, fixed in two places https://github.com/LiskHQ/lisk-desktop/pull/5366/commits/1c1aad5c9bf10fff1cccc1ebef8b2eeb53c1258a

File: src/modules/wallet/components/signMultisigView/index.js (hunk 2 above)
Comment (oskarleonard) [reply src/modules/wallet/components/signMultisigView/index.js]: Yes https://github.com/LiskHQ/lisk-desktop/pull/5366/commits/1c1aad5c9bf10fff1cccc1ebef8b2eeb53c1258a

File: src/modules/transaction/components/Multisignature/Multisignature.js [hunk 3]
```diff
@@ -114,7 +195,27 @@ const Multisignature = ({
...
+      {nextAccountToSign && (
+        <div className={styles.requiredAccountSection}>
+          <WarningNotification
+            isVisible
+            message={
+              <span>
+                {t('A required signatory account')}{' '}
+                <b>
+                  ({nextAccountToSign?.metadata?.name} -
+                  {truncateAddress(nextAccountToSign?.metadata?.address)})
```
Comment (ikem-legend) [inline src/modules/transaction/components/Multisignature/Multisignature.js:182]: Some space should be added before the account address to maintain consistency with the account name. For example, `genesis1 -lsk5px...bz76y` should be `genesis1 - lsk5px...bz76y`

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]
## Review comment

- I feel weird not having the copy button at this stage since the download button exists I think also having the copy would be nice to have
image

- I think in a situation where a user can switch instead of having `share` I think it should be `switch`
image

- Even after switching, I am still on the same account that previously has a signature collected
image

- This UI seems off 
image

**Review by ManuGowda — COMMENTED** [review]
Screenshot 2023-10-11 at 1 39 14 PM

**Review by ManuGowda — COMMENTED** [review]
Editing HW mulitisignature account crashes

Screenshot 2023-10-11 at 1 52 10 PM

File: src/modules/transaction/components/Multisignature/Multisignature.js (hunk 3 above)
Comment (oskarleonard) [reply src/modules/transaction/components/Multisignature/Multisignature.js:182]: Fixed

File: src/modules/account/hooks/useAccounts.test.js [hunk 4]
```diff
@@ -50,6 +50,13 @@ describe('useAccount hook', () => {
     expect(account).toMatchObject(mockSavedAccounts[0]);
   });
 
+  it('Should return specific account selected by pubkey', async () => {
+    const { getAccountByPublicKey } = result.current;
+    const address = mockSavedAccounts[0].metadata.pubkey;
```
Comment (ikem-legend) [inline src/modules/account/hooks/useAccounts.test.js]: Please rename constant accordingly `const publicKey = ....`

Comment (oskarleonard) [reply src/modules/account/hooks/useAccounts.test.js]: fixed

**Review by ManuGowda — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
