### PR TITLE
Fix unlock transaction transformers - Closes #3492, #3493, #3476

### LINKED ISSUE #3492: Fix transactions for uninitialized accounts
### Expected behavior
Users should be able to send transactions using the app.

### Actual behavior
Users with uninitialized accounts are unable to send any transactions.

### PR DESCRIPTION
**Pull request by UsamaHameed**
### What was the problem?
This PR resolves #3492, #3493, #3476

### How was it solved?
- Properly convert transactions for unlock 
- Properly extract public key for accounts that are uninitialized

### How was it tested?
Unit + Manually

### CODE REVIEW

**Review by isalga — DISMISSED** [review]

File: src/utils/api/account/lsk.js [hunk 1]
```diff
@@ -79,15 +80,21 @@ export const getAccount = async ({
       params: normParams,
     });
 
-    return response.data[0];
+    if (response.data[0]) {
+      const account = { ...response.data[0] };
+      const isAccountUninitialized = !account.summary?.publicKey;
```
Comment (reyraa) [inline src/utils/api/account/lsk.js:85]: Since you assumed `response.data[0]` is an object, then the account existed and `account.summary` is an object too. You don't need the null check.

File: src/utils/api/account/lsk.js [hunk 2]
```diff
@@ -79,15 +80,21 @@ export const getAccount = async ({
...
+    }
   } catch (e) {
     // eslint-disable-next-line no-console
     console.log('Lisk account not found.');
-    let publicKey = params.publicKey;
-    if (!publicKey && params.passphrase) {
-      publicKey = extractPublicKey(params.passphrase);
-    }
 
+    const publicKey = params.publicKey ?? extractPublicKey(params.passphrase);
```
Comment (reyraa) [inline src/utils/api/account/lsk.js:97]: If the method is called with address and it returned 404, this assignment will throw. The previous one was better, although it didn't look as dope.

File: src/utils/api/account/lsk.js [hunk 3]
```diff
@@ -79,15 +80,21 @@ export const getAccount = async ({
       params: normParams,
     });
 
-    return response.data[0];
+    if (response.data[0]) {
+      const account = { ...response.data[0] };
+      const isAccountUninitialized = !account.summary?.publicKey;
+      if (isAccountUninitialized) {
+        const publicKey = params.publicKey ?? extractPublicKey(params.passphrase);
```
Comment (reyraa) [inline src/utils/api/account/lsk.js:87]: If the method is called with address and it's not initialized, this will throw.

**Review by reyraa — CHANGES_REQUESTED** [review]

File: src/utils/api/account/lsk.js (hunk 2 above)
Comment (UsamaHameed) [reply src/utils/api/account/lsk.js:97]: Can you please explain 1. why do you think the assignment will throw 2. why the previous one was better (except readability)?

File: src/utils/api/account/lsk.js (hunk 3 above)
Comment (UsamaHameed) [reply src/utils/api/account/lsk.js:87]: This is fine. We can not convert the address to public key or passphrase ourselves. The consumer of the method needs to be aware of this. Thats why we throw an error at the end of the function.

**Review by reyraa — APPROVED** [review]

**Review by isalga — APPROVED** [review]
