### PR TITLE
Change commission summary modal width

### LINKED ISSUE #5512: Commission change modal to narrow
### Expected behavior
The window should be wide enough to show whole publickey
### Actual behavior
commsion modal

### Steps to reproduce
Try changing commission with a multisig account
### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop 3.0.0-rc.5, Windows

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5512

### How was it solved?

Dont use small modal on Transaction Summary step

### How was it tested?

1. Go to changeCommission modal with a multi sig account
2. Expected: Should not cut pubkey

### CODE REVIEW

**Review by ikem-legend — APPROVED** [review]

File: src/modules/pos/validator/hooks/useCurrentCommissionPercentage.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ export const useCurrentCommissionPercentage = (address) => {
   const config = { params: { address: address ?? currentAccount?.metadata?.address } };
   const { data, ...others } = useValidators({ config });
   const currentCommission = useMemo(
-    () => convertCommissionToPercentage(data?.data[0].commission),
+    () => convertCommissionToPercentage(data?.data[0]?.commission),
```
Comment (Balanced02) [inline src/modules/pos/validator/hooks/useCurrentCommissionPercentage.js:11]: is data the full query response? if so, it'll be better to have data?.data in our dependency array and not just data, as this will watch all other methods/props in the response which also includes other methods. This might not help the memo at all and it's better just having it on a variable itself...

Approving though, not a blocker, you can decide if you want to switch

**Review by Balanced02 — APPROVED** [review]

File: src/modules/pos/validator/hooks/useCurrentCommissionPercentage.js (hunk 1 above)
Comment (oskarleonard) [reply src/modules/pos/validator/hooks/useCurrentCommissionPercentage.js:11]: Yes, would be better to just have `commission` probably. This change i made is just to prevent a crash on page refresh, want to limit changes to only bugs at this stage.
