### PR TITLE
Fix wallet connect UX and security issues

### LINKED ISSUE #5138: Wallet Connect integration accepts any namespaces
### Description

The lisk-desktop wallet supports only the lisk namespace; however, it does not reject WalletConnect connections that have other requiredNamespaces . As specified in WalletConnect's documentation , wallets should reject connections from dApps that request
namespaces that the wallet does not support.

Trying to sign transactions or messages with the solana methods returns an error.

### Recommendation

Reject any WalletConnect connection request that requires any namespace that is different from lisk

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5138 #5137 #5139

### How was it solved?

- Refactored `ConnectionSummary/index.js` by moving functions below variable declaration so it is consistent
- Check if only Lisk is trying to connect and show an error view if not
- Remove pairing when user clicks cancel on the connect modal

#### Error state OK? (#5138 #5137)
1. Run wallet connect app
2. Run lisk desktop
3. Wallet connect app: Select both solana and lisk in the 
- image
4. Wallet connect app: Click connect -> new pairing -> copy to clipboard
5. Lisk desktop: Go to http://0.0.0.0:8080/#/applications?tab=SessionManager
6. Click connect wallet -> paste from your clipboard -> click connect 
7. EXPECTED: An error view should be shown

#### Success state OK? (#5138 #5137)
1. Do the above but only generate the URI for lisk in Wallet connect app
2. EXPECTED: No error view, should be able to select an account and successfully connect

#### Should be possible to reject a connection (#5139)
1. Get a URI for Lisk app (in wallet connect)
2. Try to connect with that URI on o http://0.0.0.0:8080/#/applications?tab=SessionManage
3. Instead of clicking connect, click cancel.
4. Create a new pairing with lisk in wallet connect and try to connect with that new URI
5. EXPECTED: Should be able to connect new pairing.

### CODE REVIEW

File: src/modules/blockchainApplication/connection/components/ConnectionProposal/index.js [hunk 1]
```diff
@@ -43,13 +66,21 @@ const ConnectionProposal = () => {
...
               value={value}
               className={styles.input}
               placeholder={t('Enter connection URI')}
             />
-            <span className={styles.feedback}>{status?.message}</span>
-            <PrimaryButton onClick={clickHandler} disabled={value.length === 0 || status.isPending}>
+            {nameSpaceError && (
+              <span className={styles.feedback}>
+                <span className={styles.feedbackErrorColor}>{nameSpaceError}</span>
+                <span> {t('Please enter a supported dApp URI')}</span>
```
Comment (ManuGowda) [inline src/modules/blockchainApplication/connection/components/ConnectionProposal/index.js]:
```suggestion
                <span> {t('Please enter a supported blockchain app URI.')}</span>
```

Since we are naming blockchain app everywhere lets have the same for consistency.

File: src/modules/blockchainApplication/connection/components/ConnectionProposal/index.js [hunk 2]
```diff
@@ -8,30 +8,53 @@ import { addSearchParamsToUrl } from 'src/utils/searchParams';
...
+    const event = events?.length && events[events.length - 1];
+    const requiredNamespaces = event?.meta?.params?.requiredNamespaces;
+    const nameSpaceKeys = requiredNamespaces && Object.keys(requiredNamespaces);
+    const hasNameSpaceError =
+      !nameSpaceKeys || nameSpaceKeys.length > 1 || !nameSpaceKeys.includes('lisk');
+    const isSesssionProposal = event?.name === EVENTS.SESSION_PROPOSAL;
+
+    if (isSesssionProposal && hasNameSpaceError) {
+      setValue(`wc:${event?.meta?.params?.pairingTopic}`);
+      setNameSpaceError(t('You are trying to connect to an unsupported dApp.'));
```
Comment (ManuGowda) [inline src/modules/blockchainApplication/connection/components/ConnectionProposal/index.js]:
```suggestion
      setNameSpaceError(t('You are trying to connect to an unsupported blockchain app.'));
```

**Review by ManuGowda — COMMENTED** [review]
Following scenarions needs to be handled

- Clicking outside the modal keeps the connection alive
- Entering invalid pair URI and reentering valid pair URI doesn't allow connection

**Review by ManuGowda — APPROVED** [review]
