### PR TITLE
Fix dashboard after api module refactor - Closes #3228 & #3229

### LINKED ISSUE #3228: Dashboard: news feeds is not displayed
### Expected behavior
Should display news

### Actual behavior
News feeds appears empty

### Steps to reproduce
- Log in
- Go to dashboard

### Which version(s) does this affect? (Environment, OS, etc...)
`2890-support-sdk-4`

### PR DESCRIPTION
**Pull request by isalga**
### What was the problem?
This PR resolves #3228 and #3229 

### How was it solved?
- Implement getNews method
- Fix icon condition

### How was it tested?
Add unit test

### CODE REVIEW

File: src/components/screens/dashboard/newsFeed/newsFeed.js [hunk 1]
```diff
@@ -15,18 +15,15 @@ const NewsFeed = (props) => {
     newsFeed,
     t,
   } = props;
-  const filteredNewsFeed = newsFeed.data || [];
+  const filteredNewsFeed = newsFeed.data.data || [];
```
Comment (UsamaHameed) [inline src/components/screens/dashboard/newsFeed/newsFeed.js:18]: Can we use the `withData` `transformResponse` function here to only get data instead of `data.data`?

**Review by UsamaHameed — CHANGES_REQUESTED** [review]

File: src/components/screens/dashboard/newsFeed/newsFeed.js (hunk 1 above)
Comment (isalga) [reply src/components/screens/dashboard/newsFeed/newsFeed.js:18]: Some lines below it needs error `newsFeed.error` thus transformResponse would get rid of it.

**Review by UsamaHameed — APPROVED** [review]
