### PR TITLE
Fix fee token symbol

### LINKED ISSUE #5305: Incorrect transaction fee symbol and TokenID used
### Expected behavior

- Use tokenID and metadata based on `fee-estimate` endpoint
- For other scenarios use `/fees` endpoint to get the native fee tokenID
- The `to application` list should contain the mainchain as one could transfer back the mainchain token

### Steps to reproduce

- Send enevti token on eventi chain 
Screenshot 2023-09-08 at 3 12 15 PM

- The `to application` list also do not contain the mainchain

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5305

### How was it solved?

- [x] Fix fee token symbol
- [x] Refactor environment variable usage
- [x] Resolve unit tests

### How was it tested?

- Initiate a send token flow. Fees token symbol should be correct.

### CODE REVIEW

File: src/modules/transaction/components/TransactionPriority/FeeViewer.js [hunk 1]
```diff
@@ -55,9 +55,9 @@ const FeesViewer = ({
   const { t } = useTranslation();
   const [showEditIcon, setShowEditIcon] = useState(false);
   const composedFeeList = fees.filter(({ isHidden }) => !isHidden);
-  const transactionFeeList = composedFeeList.find(
-    ({ title }) => title === 'Transaction'
-  )?.components;
+  // const transactionFeeList = composedFeeList.find(
```
Comment (oskarleonard) [inline src/modules/transaction/components/TransactionPriority/FeeViewer.js]: comments

File: .eslintrc [hunk 2]
```diff
@@ -4,6 +4,7 @@
   "plugins": ["import", "babel", "jest", "prettier"],
```
Comment (oskarleonard) [inline .eslintrc:4]: NRTTL
Now we get dupplicate when on mainchain 
image

File: src/modules/token/fungible/components/SendForm/SendForm.js [hunk 3]
```diff
@@ -214,7 +222,7 @@ const SendForm = (props) => {
                   onChange={(value) => setRecipientChain(value)}
                   select={(selectedValue, option) => selectedValue?.chainID === option.chainID}
                 >
-                  {applications.map((application) => (
+                  {[mainChainApplication, ...applications].map((application) => (
```
Comment (oskarleonard) [inline src/modules/token/fungible/components/SendForm/SendForm.js]: Are there some states where  mainChainApplication can be undefined? If line 79 fails to find an application?
In that case the first iteration will make `application` undefined and the app will crash. 
maybe 
`const allApplications = mainChainApplication ? [mainChainApplication, ...applications] : [...applications]`

Comment (eniolam1000752) [reply src/modules/token/fungible/components/SendForm/SendForm.js]: actually main chain can't be undefined because if its undefined it means application bootstrap would fail.

File: src/modules/transaction/components/TxComposer/index.js [hunk 4]
```diff
@@ -89,6 +90,15 @@ const TxComposer = ({
     extraCommandFee: formProps.extraCommandFee,
   });
 
+  const { data: { data: feeTokens } = {} } = useTokenBalances({
+    config: { parmas: { tokenID: feeTokenID, limit: 1 } },
+  });
+  const { data: { data: messageFeeTokens } = {} } = useTokenBalances({
+    config: { parmas: { tokenID: messageFeeTokenID, limit: 1 } },
+  });
```
Comment (ManuGowda) [inline src/modules/transaction/components/TxComposer/index.js]: typo in `parmas`, should be params

File: app/src/modules/win.js [hunk 5]
```diff
@@ -29,7 +29,7 @@ const win = {
     });
```
Comment (oskarleonard) [inline app/src/modules/win.js:29]: NRTTL:
Switching destination application (first time switching to that application, consecutive switches preserves the amount) nullifies the sending amount.

**Review by ManuGowda — DISMISSED** [review]

File: src/modules/pos/validator/components/UnlockBalanceForm/unlockBalance.test.js [hunk 6]
```diff
@@ -55,7 +55,7 @@ describe('Unlock LSK modal', () => {
   let wrapper;
   useTransactionPriority.mockImplementation(() => [
     { selectedIndex: 1 },
-    () => {},
+    () => { },
```
Comment (oskarleonard) [inline src/modules/pos/validator/components/UnlockBalanceForm/unlockBalance.test.js]: remove empty space inside object

File: src/modules/wallet/components/overview/overview.js [hunk 7]
```diff
@@ -128,7 +128,11 @@ const Overview = ({ isWalletRoute, history }) => {
           </div>
           <div className={`${grid['col-xs-3']} ${grid['col-md-3']} ${grid['col-lg-3']}`}>
             <DialogLink
-              data={{ message: t('There are no tokens to send at this moment.') }}
+              data={
```
Comment (oskarleonard) [inline src/modules/wallet/components/overview/overview.js:131]: Maybe we should also do this check in `accountMenu.js` as well

**Review by oskarleonard — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
