### PR TITLE
Bug fix: verify routes on deep linking navigation

### LINKED ISSUE #5117: Improper handling of the custom lisk: protocol in lisk-desktop
### Description

The lisk: protocol handler does not sufficiently validate the incoming data and has a bug that prevents some functionality from working properly.

### Actual behavior

```
const handleProtocol = () => {
    // Protocol handler for MacOS
    app.on('open-url', (event, url) => {
        event.preventDefault();
        win.browser?.show();
        win.send({ event: 'openUrl', value: url });
    });
};
```

The renderer process will minimally process the URL and use it to redirect to another path of the application.

### Steps to reproduce

https://github.com/LiskHQ/lisk-desktop/blob/8238f41dbae0ac55449149db1a19bf0b69cda7d1/src/utils/externalLinks.js#L3-L38

https://github.com/LiskHQ/lisk-desktop/blob/8238f41dbae0ac55449149db1a19bf0b69cda7d1/src/utils/login.js#L12-L13

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5117

### How was it solved?

- whitelist and verify route on `open-url` event 

### How was it tested?

- Run the electron application `yarn build:electron && yarn start`
- Add a console.log within the open-url event in `app/src/main.js` in order to observe the response from `canExecuteDeepLinking`
- Open up another terminal and run `open "lisk://wallet/?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=1&token=0200000000000000&recipientChain=02000000"`
- `canExecuteDeepLinking` should return true
- Try different combinations of deep links to test durability of the deep link verification logic

### CODE REVIEW

File: app/src/utils.js [hunk 1]
```diff
@@ -1,7 +1,32 @@
...
+  },
+];
 
 export const setRendererPermissions = (win) => {
   win.browser.webContents.session.setPermissionRequestHandler((_, permission, callback) => {
     callback(PERMISSION_WHITE_LIST.includes(permission));
   });
 };
+
+export const canExecuteDeepLinking = (url) => {
```
Comment (ManuGowda) [inline app/src/utils.js:19]: please add tests with all possible scenarios

File: app/src/utils.js [hunk 2]
```diff
@@ -1,7 +1,39 @@
...
+  if (!foundLink) return false;
+
+  const searchParamObject = [...searchParams.entries()].reduce(
+    (result, [key, value]) => ({ ...result, [key]: value }),
+    {}
+  );
+
+  try {
+    validator.validator.validate(foundLink.validationSchema, searchParamObject);
+  } catch (exp) {
```
Comment (ManuGowda) [inline app/src/utils.js]:
```suggestion
  } catch {
```

File: app/src/utils.test.js [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+      const invalidTokenIDUrl =
+        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=1&token=00000000000&recipientChain=02000000';
+      const invalidAddressUrl =
+        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8&amount=1&token=0200000000000000&recipientChain=02000000';
+
+      expect(canExecuteDeepLinking(invalidExtraParamUrl)).toBeFalsy();
+      expect(canExecuteDeepLinking(invalildAmountUrl)).toBeFalsy();
+      expect(canExecuteDeepLinking(invalidChainIDUrl)).toBeFalsy();
+      expect(canExecuteDeepLinking(invalidTokenIDUrl)).toBeFalsy();
+      expect(canExecuteDeepLinking(invalidAddressUrl)).toBeFalsy();
```
Comment (ManuGowda) [inline app/src/utils.test.js]:
```suggestion
      const invalidDeepLinkURLs = [
        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=1&token=0200000000000000&recipientChain=02000000&test=test',
        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=test&token=0200000000000000&recipientChain=02000000',
        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=1&token=0200000000000000&recipientChain=02000',
        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=1&token=00000000000&recipientChain=02000000',
        'lisk://test?modal=send&recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8&amount=1&token=0200000000000000&recipientChain=02000000'];

      test.each(invalidDeepLinkURLs)('should return true when isValidWCURI receives %s', (invalidURL) => {
          expect(canExecuteDeepLinking(invalidURL)).toBe(false);
      });
```

Comment (eniolam1000752) [reply app/src/utils.test.js]: This method looks clean though if done this way, it would be difficult for an external person taking a look at the code to tell the difference between the urls reason why I provided variable names to each to describe them. Though I can still do what you have proposed but some things like this

```
const invalidDeepLinkURLs = [
 invalidExtraParamUrl,
 invalildAmountUrl,
 invalidChainIDUrl,
 invalidTokenIDUrl,
 invalidAddressUrl
]
```

**Review by ManuGowda — DISMISSED** [review]

File: app/src/utils.js [hunk 4]
```diff
@@ -1,7 +1,39 @@
...
+  },
+];
 
 export const setRendererPermissions = (win) => {
   win.browser.webContents.session.setPermissionRequestHandler((_, permission, callback) => {
     callback(PERMISSION_WHITE_LIST.includes(permission));
   });
 };
+
+export const canExecuteDeepLinking = (url) => {
```
Comment (oskarleonard) [inline app/src/utils.js:19]: Should it also clean invalid url params? Or completely reject those url? For example
`open "lisk://wallet?recipient=lskdb3ja5dhr25jhwm6onstawj33yk74g8q2549oc&amount=2300&token=0200000000000000&recipientChain=02000000&modal=send&name=oskar"`

Should that:
1. Dont open the send modal bc of url param `name=oskar`
2. Open send modal but clean the url from `name=oskar`
3. Behave like this PR does now, opens the send modal and keeps the `name=oskar` param

Comment (eniolam1000752) [reply app/src/utils.js:19]: done

**Review by ManuGowda — APPROVED** [review]

File: app/src/utils.js (hunk 4 above)
Comment (oskarleonard) [reply app/src/utils.js:19]: Nice

**Review by oskarleonard — APPROVED** [review]
