### PR TITLE
Incorrect js docs

### LINKED ISSUE #5190: Lisk-desktop: incorrect JDocs
### Actual behavior

Lisk-desktop makes use of JDocs to document functions; however several are malformed, missing, or include unknown parameters. 

### Steps to reproduce
Use the following CodeQL rules to find and fix these problems:
-  js/jsdoc/malformed-param-tag : Finds parameters missing a description
- js/jsdoc/missing-parameter : Finds undocumented parameters
- js/jsdoc/unknown-paramete r: Finds documented parameters that are not function argument

### PR DESCRIPTION
**Pull request by oskarleonard**
### What was the problem?

This PR resolves #5190

### How was it solved?

Removed most of our Js docs since much of it is deprecated and difficult to have up to date. Future focus will be to have self documented code with type script.

### How was it tested?

Manually

### CODE REVIEW

File: src/modules/pos/validator/store/actions/staking.js [hunk 1]
```diff
@@ -45,15 +45,9 @@ export const stakeDiscarded = (data) => ({
 
 /**
  * Defines the new stake amount for a given validator.
- * The reducer will add a new stake if if didn't exist before
+ * The reducer will add a new stake if i didn't exist before
```
Comment (ManuGowda) [inline src/modules/pos/validator/store/actions/staking.js]:
```suggestion
 * The reducer will add a new stake if it didn't exist before
```

**Review by ManuGowda — DISMISSED** [review]

**Review by ManuGowda — APPROVED** [review]

File: src/modules/auth/store/action.js [hunk 2]
```diff
@@ -5,32 +5,11 @@ import actionTypes from './actionTypes';
...
- *
- * @param {Object} data - for hardware wallets it contains publicKey and hwInfo,
- *    otherwise contains passphrase
- * @param {String} data.passphrase - BIP39 passphrase of the account
- * @param {String} data.publicKey - Lisk publicKey used for hardware wallet login
- * @param {Object} data.hwInfo - info about hardware wallet we're trying to login to
- */
-
-/**
- * Store second passphrase in the Redux store
```
Comment (eniolam1000752) [inline src/modules/auth/store/action.js:19]: I think we can still retain this line

File: src/modules/auth/store/action.js [hunk 3]
```diff
@@ -5,32 +5,11 @@ import actionTypes from './actionTypes';
...
- * @param {string} passphrase - Valid Mnemonic passphrase
- * @returns {object} Pure action object
- */
 export const secondPassphraseStored = (passphrase) => ({
   type: actionTypes.secondPassphraseStored,
   data: passphrase,
 });
 
-/**
- * Removes the second passphrase from the Redux store
```
Comment (eniolam1000752) [inline src/modules/auth/store/action.js:30]: can 't we also retain this

File: src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js [hunk 4]
```diff
@@ -2,24 +2,6 @@ import { BLOCKCHAIN_APPS } from 'src/const/queries';
 import { LIMIT as limit, API_VERSION } from 'src/const/config';
 import { useCustomInfiniteQuery } from 'src/modules/common/hooks';
 
-/**
- * Creates a custom hook for blockchain applications list queries
```
Comment (eniolam1000752) [inline src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js:6]: can't we retain this

File: src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationStatistics.js [hunk 5]
```diff
@@ -2,17 +2,6 @@ import { BLOCKCHAIN_APPS_STATISTICS } from 'src/const/queries';
 import { API_VERSION } from 'src/const/config';
 import { useCustomQuery } from 'src/modules/common/hooks';
 
-/**
- * Creates a custom hook for blockchain applications meta queries
```
Comment (eniolam1000752) [inline src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationStatistics.js:6]: can't we retain this too

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]

File: src/modules/auth/store/action.js (hunk 2 above)
Comment (oskarleonard) [reply src/modules/auth/store/action.js:19]: To me all of these descriptions are redundant.
Imo, it is better to have self documenting code, which for these cases i feel that we have.
File is in a folder called /store (so i interpret redux) and the file is called action (so i interpret functions here modifies the redux state).

How do you feel the comment brings value?

I guess `setSecondPassphrase` would have been a better name, but still `secondPassphraseStored` is understandable.

File: src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js (hunk 4 above)
Comment (oskarleonard) [reply src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js:6]: But we agreed that we should remove all this params because too many docs in the code base have incorrect values. I think it gives a false sense of security, better to just look up swagger when i need to know what parameters i can send

Comment (oskarleonard) [reply src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js:6]: Feels strange to leave it in some places and remove it in other places is mostly my concern :/

**Review by eniolam1000752 — APPROVED** [review]
