### PR TITLE
Resolved toaster display on unrelated accounts

### LINKED ISSUE #5448: Claim rewards toaster appears for unrelated account
### Expected behavior
Claim rewards toast should be removed after switching accounts

### Actual behavior
Claim rewards toast keeps displaying after switching accounts, which can be confusing

### Steps to reproduce
- Select an account with rewards to be claimed
- Switch to a different account without rewards

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #5448

### How was it solved?

- Dismissed toaster after current account is switched

### How was it tested?

- Manually

### CODE REVIEW

**Review by ManuGowda — CHANGES_REQUESTED** [review]
Toaster shown for an account that doesn't have an claim rewards.

STR
- Ensure you have an account on mainchain with claim rewards
- Switch to sidechain with same account, observe the toaster
Screenshot 2023-11-17 at 10 37 54 AM

**Comment by ikem-legend** [comment]
> Toaster shown for an account that doesn't have an claim rewards.
> 
> STR
> 
> * Ensure you have an account on mainchain with claim rewards
> * Switch to sidechain with same account, observe the toaster
>   Screenshot 2023-11-17 at 10 37 54 AM

Good catch. I've fixed it for application switch as well as network switch

**Review by ManuGowda — DISMISSED** [review]

File: src/modules/account/hooks/useCurrentAccount.js [hunk 1]
```diff
@@ -65,7 +71,10 @@ export function useCurrentAccount() {
         }
       }
     }
+    // Remove toast between account switches
+    toast.dismiss();
```
Comment (oskarleonard) [inline src/modules/account/hooks/useCurrentAccount.js]: This is the only real change in this file? Others are formatting? Just want to know because i will get merge conflict on this file if this PR is merged before my PR

File: src/modules/blockchainApplication/manage/hooks/useCurrentApplication.js [hunk 2]
```diff
@@ -40,9 +41,13 @@ export function useCurrentApplication() {
         onConfirm,
         onCancel,
       });
+      // Remove toast between application switches
+      toast.dismiss();
```
Comment (oskarleonard) [inline src/modules/blockchainApplication/manage/hooks/useCurrentApplication.js]: We probably want to do this onConfirm, not just when showing confirm switch modal

File: src/modules/network/components/networkSwitcherDropdown/NetworkSwitcherDropdown.js [hunk 3]
```diff
@@ -78,13 +79,17 @@ function NetworkSwitcherDropdown({ noLabel, onNetworkSwitchSuccess }) {
               onCancel,
               onConfirm,
             });
+            // Remove toast between network switches
+            toast.dismiss();
```
Comment (oskarleonard) [inline src/modules/network/components/networkSwitcherDropdown/NetworkSwitcherDropdown.js]: `onConfirm`

File: src/modules/account/hooks/useCurrentAccount.js (hunk 1 above)
Comment (ikem-legend) [reply src/modules/account/hooks/useCurrentAccount.js]: Yeah, they're formatting changes and some of them are enforced by our pre commit hooks

File: src/modules/blockchainApplication/manage/hooks/useCurrentApplication.js (hunk 2 above)
Comment (ikem-legend) [reply src/modules/blockchainApplication/manage/hooks/useCurrentApplication.js]: Fixed

File: src/modules/network/components/networkSwitcherDropdown/NetworkSwitcherDropdown.js (hunk 3 above)
Comment (ikem-legend) [reply src/modules/network/components/networkSwitcherDropdown/NetworkSwitcherDropdown.js]: Fixed

**Review by oskarleonard — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
