### PR TITLE
Reset selected token on log out - Closes #2984

### LINKED ISSUE #2984: Lisk monitoring features are not visible
Lisk monitoring features are not visible when i sign out.  

**Steps to reproduce**

Sign in  Lisk application, switch the network from Lisk to Bitcoin and do the sign out.

### PR DESCRIPTION
**Pull request by isalga**
### What was the problem?
This PR resolves #2984

### How was it solved?
Adding a side effect on account log out

### How was it tested?
Manual test

### CODE REVIEW

**Comment by reyraa** [comment]
@isalga The solution is smart and works as desired. but it needs to be tested.
Please amend one of the `login` e2e tests with token change scenario. Also please update the `account` middleware to test dispatching of `settingsUpdated`.

**Review by sridharmeganathan — DISMISSED** [review]

File: src/store/middlewares/account.js [hunk 1]
```diff
@@ -209,6 +211,7 @@ const accountMiddleware = store => next => (action) => {
       votePlaced(store, action);
       break;
     case actionTypes.accountLoggedOut:
+      store.dispatch(settingsUpdated({ token: { active: tokenMap.LSK.key } }));
```
Comment (UsamaHameed) [inline src/store/middlewares/account.js:214]: It would also be nice to add a comment here explaining why we switch the token when logging out (Also add the issue no may be). Looking at this, it is not very obvious why we do so.

File: test/cypress/features/login/login.js [hunk 2]
```diff
@@ -89,6 +89,23 @@ Given(/^I choose ([^\s]+)$/, function (networkName) {
   }
 });
 
+Then(/^I change active token to BTC$/, function () {
```
Comment (reyraa) [inline test/cypress/features/login/login.js:92]: Prefer `I click on` from `featurers/common`

File: test/cypress/features/login/login.js [hunk 3]
```diff
@@ -89,6 +89,23 @@ Given(/^I choose ([^\s]+)$/, function (networkName) {
...
+  cy.get(ss.lskToken).click();
+});
+
+Then(/^I log out$/, function () {
```
Comment (reyraa) [inline test/cypress/features/login/login.js:96]: Prefer `I click on` from `featurers/common`

File: test/cypress/features/login.feature [hunk 4]
```diff
@@ -56,4 +56,15 @@ Feature: Login
...
+  Scenario: Log out
+    Given showNetwork setting is true
+    Given I am on Login page
+    When I choose testnet
+    When I enter first passphrase of testnet_guy
+    When I login
+    When I am on dashboard page
+    And I change active token to BTC
+    And I log out
+    Then I should see lisk monitor features
```
Comment (reyraa) [inline test/cypress/features/login.feature:68]: E2E tests are slow and Logging in a long process. Please consider removing this scenario and simply adding the last three steps to one of the existing scenarios.

**Review by reyraa — CHANGES_REQUESTED** [review]

**Review by reyraa — APPROVED** [review]
Looks great! Thank you so much
