### PR TITLE
 Unvoting multiple delegates result in error - Closes #2634 

### LINKED ISSUE #2634: Unvoting multiple delegates result in error
### Steps to reproduce

1. Navigate to delegates page.
2. Downvote more then one delegate.
3. Submit your vote.

### Actual result
The error says argument must be a string
68479308-ebba6f00-0229-11ea-849c-84cead81073e

### Expected result
It should show an error related to voting.

### Version
1.22.0

### PR DESCRIPTION
**Pull request by reyraa**
### What issue have I solved?

Resolves #2634 

### How have I implemented/fixed it?
The data structure was wrong after the braking changes of Lisk Core. I made changes to comply.

### How has this been tested?
 - Fixed the data structure issues.
 - Updated unit tests.
Extra:
 - Fixed the issue that fired votesToggled action 3 times in a row.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by reyraa** [comment]
@slaweet Fixed both issues.

File: src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js [hunk 1]
```diff
@@ -48,7 +48,14 @@ export default class VoteUrlProcessor extends React.Component {
...
     if (filterObjectPropsWithValue(this.state.voteLookupStatus, 'pending').length === 0
         && this.state.pendingVotes.length > 0) {
-      this.state.pendingVotes.map(v => this.props.voteToggled(v));
+      this.state.pendingVotes.forEach(v => this.props.voteToggled({
+        account: {
+          address: v.address,
+          publicKey: v.publicKey,
+        },
+        username: v.username,
+        balance: v.balance,
```
Comment (slaweet) [inline src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js]: 👍 Good catch that this also needs to be updated, but 
 💅 `balance` shouldn't be here as it is not used/defined at all in `voteToggled`:
https://github.com/LiskHQ/lisk-desktop/blob/05773664095b0304a4c851e8dd084f0b9c9a2b99/src/store/reducers/voting.js#L78-L85

Comment (reyraa) [reply src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js]: Yes, but it's already passed. I didn't want to filter a part of data out while it doesn't harm to be there.

Comment (reyraa) [reply src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js]: Remove it.

Comment (slaweet) [reply src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js]: I don't see `balance` being already passed. AFAIK it is not in delegate object at all. These are the data I see if I `console.log(this.state.pendingVotes);`
Screenshot 2019-11-20 at 14 01 19

File: src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js [hunk 2]
```diff
@@ -48,7 +48,13 @@ export default class VoteUrlProcessor extends React.Component {
   componentDidUpdate() {
     if (filterObjectPropsWithValue(this.state.voteLookupStatus, 'pending').length === 0
         && this.state.pendingVotes.length > 0) {
-      this.state.pendingVotes.map(v => this.props.voteToggled(v));
+      this.state.pendingVotes.forEach(v => this.props.voteToggled({
+        account: {
+          address: v.address,
+          publicKey: v.publicKey,
+        },
+        username: v.username,
```
Comment (slaweet) [inline src/components/screens/delegates/voting/voteUrlProcessor/voteUrlProcessor.js]: 🐛 Now I noticed it needs to pass `rank` here. Else there is a regression and the page shows:

Screenshot 2019-11-20 at 14 07 32

Instead of:
Screenshot 2019-11-20 at 14 05 25
```suggestion
        username: v.username,
        rank: v.rank,
```
