### PR TITLE
Fix standby status name - Resolves #3908

### LINKED ISSUE #3908: Misalignment in standby delegate status definition
### Expected behavior
Delegates are marked as `standby` by Lisk Service, given they have a minimum delegate weight of 1000 LSK and are none of the following:
- Active
- Punished
- Banned
Lisk Desktop must follow the same logic to mark delegates whose status is not defined by Lisk Service. Also it should mark them exactly `standby`.

### Actual behavior
Lisk Desktop marks such delegates `standBy`. This causes some visual issues.

### Steps to reproduce
Refer to the [PerformanceView](https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/screens/wallet/delegateProfile/performanceView.js#L19) component.

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?

This PR resolves #3908

### How was it solved?
Changed `standBy` status to `standby`.
We are patching the API response to rename the delegate status from non-eligible to ineligible.  I've created[ a ticket](https://github.com/LiskHQ/lisk-desktop/issues/3910) to revert this.

### How was it tested?
Visually.

### CODE REVIEW

File: src/components/screens/wallet/delegateProfile/performanceView.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const getStatus = (data) => {
     return data.status;
   }
   if (data.voteWeight >= DEFAULT_STANDBY_THRESHOLD) {
-    return 'standBy';
+    return 'standby';
   }
   return 'inEligible';
```
Comment (ManuGowda) [inline src/components/screens/wallet/delegateProfile/performanceView.js:23]: does this also apply to `inEligible`? would be nice to case them similar

Comment (reyraa) [reply src/components/screens/wallet/delegateProfile/performanceView.js:23]: I can see that in Lisk Service we use `non-eligible`, although according to our last meeting we decided `ineligible` sounds more familiar to native ears. I think we should fix it there. but as for camelCase-lowercase, I can change it to `ineligible`.

**Review by ManuGowda — APPROVED** [review]
