### PR TITLE
Prevent wallet page crash - Closes #3477

### LINKED ISSUE #3477: Wallet page crash on Table component
### Expected behavior
Page should not crash

### Actual behavior
Crash after loading

```Uncaught TypeError: Cannot read property 'length' of undefined
    at Table (index.js:107)```

```<LoadMoreButton
        onClick={loadData}
        isLoading={isLoading}
        dataLength={data.length```

### Which version(s) does this affect? (Environment, OS, etc...)
feature-sdk-v5

### PR DESCRIPTION
**Pull request by isalga**
### What was the problem?
This PR resolves #3477 

### How was it solved?
- Prevent Table to receive ```undefined``` data
- Use ```data.votes``` on voting reducer

### How was it tested?
Add unit test

### CODE REVIEW

**Review by reyraa — APPROVED** [review]
Good cache.

File: src/components/toolbox/table/index.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ import styles from './table.css';
  * you can use this property.
  */
 const Table = ({
-  data,
+  data = [],
```
Comment (UsamaHameed) [inline src/components/toolbox/table/index.js:66]: we probably need to add another test to cover this code branh

**Review by UsamaHameed — CHANGES_REQUESTED** [review]

**Review by UsamaHameed — APPROVED** [review]
