### PR TITLE
Fix zero custom fee

### LINKED ISSUE #5447: I am able to edit to a zero fee value on edit multisignature
### Expected behavior
I should not be able to edit the fee to a value lesser than the minimum required fee estimated by service

### Actual behavior
I am able to edit the fee to even a zero value (i.e a value even lesser than the minimum required fee estimate value. 

### Steps to reproduce
- Navigate to edit multi-signature account
- Click on custom on the fee viewer
- Edit the fee value to zero

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5447, #5472

### How was it solved?

- [x] Fix conditional statement in getCustomFeeStatus
- [x] Fix request token issue on no tokens view

### How was it tested?

- Initiate any transaction
- Enable custom fee
- Try to edit custom fee to zero
- You should not be able to commit a zero fee value

### CODE REVIEW

**Review by ikem-legend — DISMISSED** [review]

File: src/modules/transaction/components/TransactionPriority/FeeViewer.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { validateAmount } from 'src/utils/validators';
 import styles from './TransactionPriority.css';
 
 const getCustomFeeStatus = ({ customFeeInput, minFee, minRequiredBalance, token }) => {
-  if (!customFeeInput || !token || !minRequiredBalance) return undefined;
```
Comment (ManuGowda) [inline src/modules/transaction/components/TransactionPriority/FeeViewer.js:14]: If we remove `minRequiredBalance` check it might fail with `accountBalance: BigInt(token.availableBalance) - BigInt(minRequiredBalance),`?

Comment (eniolam1000752) [reply src/modules/transaction/components/TransactionPriority/FeeViewer.js:14]: nope it does not fail

**Review by ManuGowda — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]
