### PR TITLE
Fix table load more button - Closes #2669

### LINKED ISSUE #2669: Monitoring: Load more button is not shown after several fetchings
### Expected behavior
Load more is always there
### Actual behavior
It is not shown after several uncertain number of loadings
### Steps to reproduce
1. Go to monitoring
1. Blocks
1. Click Load more until you cant see the button
### Which version(s) does this affect? (Environment, OS, etc...)
1.23.0

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?
This PR resolves #2669 

### How was it solved?
- Remove the %30 condition
- Control the button in parent components

### How was it tested?
Manual and using unit tests

### CODE REVIEW

File: src/components/screens/monitor/blockDetails/blockDetails.js [hunk 1]
```diff
@@ -125,6 +125,7 @@ const BlockDetails = ({
         title={t('Transactions')}
         transactions={blockTransactions}
         emptyStateMessage={t('There are no transactions for this block.')}
+        canLoadMore={false}
```
Comment (slaweet) [inline src/components/screens/monitor/blockDetails/blockDetails.js]: It's an edge case, but the genesis block (height=1) has more than 30 transactions, so it might be worth to have that covered

Comment (reyraa) [reply src/components/screens/monitor/blockDetails/blockDetails.js]: Thanks. I forgot about genesis block. Fixed it.
