### PR TITLE
Bugfix related to transaction overview, dryrun and error report

### LINKED ISSUE #5251: Transaction overview doesn't show statistics
### Expected behavior

Transaction overview should show stats even when an account is not added

### Actual behavior

Screenshot 2023-07-07 at 12 09 54 PM

### Steps to reproduce

Download the wallet and ensure you do not have any accounts added to wallet. Navigate to transactions tab and observer the stats.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5251, #5256 and #5257

### How was it tested?

- Overview bug: open app in incognito window without any accounts and check if you can view all the stats of transaction
- Dry run: Use transaction composer to modify the fee to be lower and other kinds of scenario to test how dry run results are handled
- Error report: Send a transaction that is invalid and check if Retry works and also report email should show valid information like chain name, id, url and transaction and error message when exists.

### CODE REVIEW

File: src/modules/legacy/components/Summary/Summary.js [hunk 1]
```diff
@@ -34,8 +34,11 @@ const Summary = ({ balanceReclaimed, nextStep, wallet, t, fees }) => {
     }),
     [wallet.legacy?.balance, module, command, wallet.sequence?.nonce, wallet.summary?.publicKey]
   );
+  const { data: networkFees } = useFees();
+
   const { initializationFees } = useGetInitializationFees({
     address: wallet.summary?.address,
+    tokenID: networkFees?.data?.feeTokenID,
   });
```
Comment (eniolam1000752) [inline src/modules/legacy/components/Summary/Summary.js]: aren't we suppose to invoke the fee estimate endpoint here. Though I think the above still works though

File: src/utils/validators.js [hunk 2]
```diff
@@ -110,6 +114,19 @@ export const validateAmount = ({
         return MIN_ACCOUNT_BALANCE > BigInt(accountBalance) - BigInt(amountInBase);
       },
     },
+    FEE_RANGE: {
+      message: i18n.t(
+        `Fee must be greater than ${convertFromBaseDenom(
+          minValue,
+          token
+        )} and less than ${convertFromBaseDenom(accountBalance, token)}.`
+      ),
```
Comment (eniolam1000752) [inline src/utils/validators.js]: shouldn't this be provided via interpolation

```suggestion
      message: i18n.t(
        `Fee must be greater than {{ maxFee }} and less than {{ minFee }}.`,
        {
          minFee: convertFromBaseDenom(accountBalance, token),
          maxFee: convertFromBaseDenom(
            minValue,
            token
          ),
        }
      ),
```

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]

**Review by eniolam1000752 — DISMISSED** [review]

**Review by ikem-legend — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
