### PR TITLE
Fixed the amount range - Closes #4196

### LINKED ISSUE #4196: The transaction amount distribution is inacurate
### Expected behavior
The value ranges should be:
0 - 10LSK
11 - 100LSK
101 - 1000LSK

### Actual behavior
The value ranges current are:
0 - 10LSK
10 - 100LSK
 and so on.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3.0

### PR DESCRIPTION
**Pull request by vibratious**
### What was the problem?

This PR resolves #4196

### How was it solved?

I fixed the amount range according to the ticket description

### How was it tested?
visually

### CODE REVIEW

**Review by ikem-legend — DISMISSED** [review]

**Review by eniolam1000752 — APPROVED** [review]
LGTM

**Review by gadjacobs — APPROVED** [review]

**Comment by reyraa** [comment]
@ElnazShahidian Thank you for contributing in Lisk Desktop. I had to change the base branch and now your PR has a conflict. Please be so kind and fix the conflict. Thank you

**Review by gadjacobs — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
LGTM

File: src/components/screens/monitor/transactions/overview/overview.js [hunk 1]
```diff
@@ -104,14 +104,14 @@ const normalizeNumberRange = (distributions) => {
...
-    '1000_10000': '1000K - 10,000 LSK',
-    '10000_100000': '10,000 - 100,000 LSK',
-    '100000_1000000': '100,000 - 1,000,000 LSK',
-    '1000000_10000000': '1,000,000 - 10,000,000 LSK',
-    '10000000_100000000': '10,000,000 - 100,000,000 LSK',
-    '100000000_1000000000': '100,000,000 - 1,000,000,000 LSK',
+    '10_100': '11 - 100 LSK',
+    '100_1000': '101 - 1000 LSK',
+    '1000_10000': '1001 - 10,000 LSK',
+    '10000_100000': '10,001 - 100,000 LSK',
```
Comment (ikem-legend) [inline src/components/screens/monitor/transactions/overview/overview.js:110]: @ElnazShahidian Since we're adding commas to all the larger numbers, we might as well do so for `1000` and `1001`

Comment (reyraa) [reply src/components/screens/monitor/transactions/overview/overview.js:110]: Good point

Comment (vibratious) [reply src/components/screens/monitor/transactions/overview/overview.js:110]: I think it would be ugly and I haven't seen anyone do it for 1k

Comment (ikem-legend) [reply src/components/screens/monitor/transactions/overview/overview.js:110]: @vibratious Fair enough

**Review by ikem-legend — APPROVED** [review]
