### PR TITLE
Fix recovery phrase text word count and rewards amount formatting

### LINKED ISSUE #4959: Recovery phrase text should have the right count of words in the recovery phrase
### Expected behavior
Creating new account returns 24 word passphrase but text should suggest writing down the correct number of words

### Actual behavior
Creating new account returns 24 word passphrase but text suggests writing down 12 words
lisk-app-test-fdbk-6

### Steps to reproduce
- Visit the Add new account page
- Create new account
- Navigate to secret recovery phrase page

### Which version(s) does this affect? (Environment, OS, etc...)
All

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #4959 and #4963

### How was it solved?

- Updating description text
- Implementing amount formatting

### How was it tested?

- Visually

### CODE REVIEW

File: src/modules/wallet/components/passphraseRenderer/index.js [hunk 1]
```diff
@@ -145,7 +145,7 @@ class PassphraseRenderer extends React.Component {
             <h2 className={styles.header}>{t('Secret recovery phrase')}</h2>
             {subheader && (
               <p className={styles.subheader}>
-                {t('Please write down these 12 words carefully, and store them in a safe place.')}
+                {t('Please write down these 24 words carefully, and store them in a safe place.')}
```
Comment (ManuGowda) [inline src/modules/wallet/components/passphraseRenderer/index.js]: This can be problem, user can have both 12 and 24 words? you need dynamically render this text based on phrase length

Comment (ManuGowda) [reply src/modules/wallet/components/passphraseRenderer/index.js]: 12/24

File: src/modules/wallet/components/passphraseRenderer/index.js [hunk 2]
```diff
@@ -145,7 +145,9 @@ class PassphraseRenderer extends React.Component {
             <h2 className={styles.header}>{t('Secret recovery phrase')}</h2>
             {subheader && (
               <p className={styles.subheader}>
-                {t('Please write down these 12 words carefully, and store them in a safe place.')}
+                {t(
+                  'Please write down these 12/24 words carefully, and store them in a safe place.'
+                )}
```
Comment (ManuGowda) [inline src/modules/wallet/components/passphraseRenderer/index.js]:
```suggestion
                  'Please write down these seed values carefully. Ensure that you keep this in a safe place, with access to the seed you can re-create the account.
                )}
```

I think this more generic in my opinion.

**Review by ManuGowda — COMMENTED** [review]
rest LGTM

**Review by ManuGowda — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]
