### PR TITLE
Fix the visual issues with the dark mode - Closes #2648,  #2679, #2622

### LINKED ISSUE #2622: Use new illustrations provided by design team
### Description
The design team have provided us with [new illustrations](https://trello.com/c/LQhPsquq/76-new-illustrations-for-hub-onboarding) for onboarding slides and other places. This ticket aims to replace the old ones with the aforementioned new assets.

### LINKED ISSUE #2648: Add dark mode version of illustration to the app
### Description
The current set of illustrations are not ready for dark mode. the design team have provided us with new illustrations which suit both themes. we need to replace these assets and ensure everything works fine.

### LINKED ISSUE #2679: Fix visual issues with the dark mode
### Description
The basic changes required for the dark mode is implemented by #2579 but there are a lot of visual issue remaining. These issues include
-  Icons should follow the theme
- illustrations should follow the theme
- QR code needs improvements
- Buttons and inputs need changes to adapt the theme.
- The on-boarding slides need some changes.
- The loading component is not ready for dark mode.
- The typography colors needs to change in dark mode.

### PR DESCRIPTION
**Pull request by reyraa**
### What issue have I solved?

Resolves #2648 
Resolves #2679
Resolves #2622

### How have I implemented/fixed it?
 - Altered the icons
 - Altered illustrations
 - Fixed the color of CR codes
 - Fixed the styles of buttons
 - Fixed the styles of inputs
 - Fixed the colors of on-boarding sliders
 - Fixed the loading bg in Box component (When loading Tx, blocks, accounts or delegates)
 - Fixed some text colors in the wallet page.
 - Added unit tests for WalletDetails
 - Added unit tests for Icon and Illustration

### How has this been tested?
Compared the implementation with designs in InVision.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/app/index.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ class App extends React.Component {
 
   render() {
     const { location, history, settings } = this.props;
-    const theme = settings.DarkMode ? 'dark' : 'light';
+    const theme = settings.darkMode ? 'dark' : 'light';
```
Comment (slaweet) [inline src/app/index.js]: 💡 I think it would make it easier to handle the `isSigninFlow` here:
```suggestion
    const theme = settings.darkMode && !routeObj.isSigninFlow ? 'dark' : 'light';
```

It would mean:
- no need to pass `isSigninFlow` to `OfflineWrapper` and `theme` HOC
- no need for `noTheme` prop on `Icon` in `signInHeader.js`
