### PR TITLE
Fix load more on received votes section - Closes #4514

### LINKED ISSUE #4514: The load more button is the delegate page misfunctions
### Expected behavior
- If the entire list of voters/votes are loaded, I should not see the load more buttons.
- Duplicated items must not be added.

### Actual behavior
- I see the load more button where unnecessary.
- When I click, it loads the same items again.

### Steps to reproduce

https://user-images.githubusercontent.com/666685/196415751-e3ee725c-d2c7-4697-a299-be5b586c2ef9.mov

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4514

- [x] investigate cause of issue from received votes response
- [x] fix redirection path when voter is clicked
- [x] fix break on wallet overview page

visually

### CODE REVIEW

File: src/modules/wallet/components/overview/overview.js [hunk 1]
```diff
@@ -55,11 +51,11 @@ const Overview = ({ isWalletRoute, history }) => {
 
   const isBanned = delegate.isBanned;
   const pomHeights = delegate.pomHeights;
-  const { end } = pomHeights ? pomHeights[pomHeights.length - 1] : 0;
+  const { end } = pomHeights && pomHeights.length ? pomHeights[pomHeights.length - 1] : {};
 
   const daysLeft = Math.ceil((end - currentHeight) / numOfBlockPerDay);
   const wallet = useSelector(selectActiveTokenAccount);
-  const { data: tokens, isLoading, error } = useTokensBalance();
+  const { data: tokens, isLoading, error } = useTokensBalance({ config: { params: { address } } });
```
Comment (ikem-legend) [inline src/modules/wallet/components/overview/overview.js:58]:
```suggestion
  const { end } = pomHeights?.length ? pomHeights[pomHeights.length - 1] : {};
```

File: src/modules/wallet/components/overview/overview.js [hunk 2]
```diff
@@ -55,11 +51,11 @@ const Overview = ({ isWalletRoute, history }) => {
 
   const isBanned = delegate.isBanned;
   const pomHeights = delegate.pomHeights;
-  const { end } = pomHeights ? pomHeights[pomHeights.length - 1] : 0;
+  const { end } = pomHeights && pomHeights.length ? pomHeights[pomHeights.length - 1] : {};
```
Comment (ikem-legend) [inline src/modules/wallet/components/overview/overview.js]:
```suggestion
  const { end } = pomHeights?.length ? pomHeights[pomHeights.length - 1] : {};
```

**Review by ikem-legend — APPROVED** [review]

File: src/modules/wallet/components/overview/overview.js [hunk 3]
```diff
@@ -95,7 +91,7 @@ const Overview = ({ isWalletRoute, history }) => {
           availableBalance={availableBalance}
           lockedBalance={totalLockedBalance}
           address={address}
-          symbol={symbol}
+          symbol={symbol || ''}
```
Comment (Balanced02) [inline src/modules/wallet/components/overview/overview.js:94]: ...why an empty string here?

**Review by Balanced02 — APPROVED** [review]
