### PR TITLE
Fix issues observed on 3.0.0-rc.3

### LINKED ISSUE #5429: Invalid column name on transaction table
### Expected behavior
The first column of the transactions table in the overview page should be `Sender` not `Recipient`

### Actual behavior
The first column of the transactions table says `Recipient`

### Steps to reproduce
- Navigate to the wallets page you would see that the first column is `Recipient`

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5429, #5427, #5426, #5425 and #5419

### How was it solved?

- Added validation to multi-signature required signature input field
- Fix block transactions header alignment
- Fix first column of the wallet's page transaction table
- Fix issue with sign message

### CODE REVIEW

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js [hunk 1]
```diff
@@ -108,12 +108,14 @@ const TxSignatureCollector = ({
   };
 
   const onEnterPasswordSuccess = ({ privateKey }) => {
-    const paramsSchema = moduleCommandSchemas[moduleCommand];
-    const transaction = fromTransactionJSON(transactionJSON, paramsSchema);
-    const buffer = encodeTransaction(transaction, paramsSchema);
-    const transactionHex = cryptography.utils.hash(buffer).toString('hex');
-    if (isTransactionAuthor) {
-      incrementNonce(transactionHex);
+    if (transactionJSON.nonce) {
```
Comment (ManuGowda) [inline src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js]: I think this was not the bug? we need to find the root cause?

it could be the `isTransactionAuthor` which is declared in global scope? please check the root of the problem and fix

File: src/modules/wallet/components/RegisterMultisigForm/index.js [hunk 2]
```diff
@@ -124,6 +126,12 @@ const Form = ({ nextStep, prevState = {}, onNext, authQuery }) => {
   const changeNumberOfSignatures = (e) => {
     const value = e.target.value ? Number(e.target.value) : undefined;
 
+    if (value > 64) {
+      setRequiredSignatureError('Cannot have more than 64 required signature');
```
Comment (ManuGowda) [inline src/modules/wallet/components/RegisterMultisigForm/index.js]: Use the constant MAX_MULTI_SIG_MEMBERS

**Review by ManuGowda — CHANGES_REQUESTED** [review]
The status column value needs to be aligned 

Screenshot 2023-11-13 at 9 11 33 AM

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js (hunk 1 above)
Comment (oskarleonard) [reply src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js]: Is this one related to signing a message? I think it is a good idea to move that logic inside the if statement because it is not used outside of the if. However, should we not still use `if(isTransactionAuthor)`

**Review by oskarleonard — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
