### PR TITLE
Fix auto sign out option in settings page - Closes #3965

### LINKED ISSUE #3965: Auto sign out is not working in setting page
### Expected behavior
Allow users to check/uncheck auto sign out option 

### Actual behavior
users are unable to uncheck the auto sign out option in setting page

### Steps to reproduce
- select the settings option from the side bar and try to uncheck auto sign out

### Which version(s) does this affect? (Environment, OS, etc...)
v2.2.0-beta.0

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?

This PR resolves #3965

### How was it solved?

The account wasn't passed via the HOC.

### CODE REVIEW

File: src/components/screens/settings/index.js [hunk 1]
```diff
@@ -7,6 +7,11 @@ import Settings from './settings';
 const mapStateToProps = state => ({
   settings: state.settings,
   transactions: state.transactions,
+  account: {
```
Comment (ManuGowda) [inline src/components/screens/settings/index.js:10]: import { getActiveTokenAccount } from '@utils/account';

`account: getActiveTokenAccount(state),`

Comment (reyraa) [reply src/components/screens/settings/index.js]: Done

**Review by ManuGowda — APPROVED** [review]

**Review by isalga — APPROVED** [review]
