### PR TITLE
Aligning empty states - Closes #2704

### LINKED ISSUE #2704: Aligning empty states
### Expected behavior

🎨 Both should have the same behaviour, showing illustration + copy

### Actual behavior

🎨 Typography looks different and illustration is missing in the wallet page. Screenshots as reference below:

Screenshot 2019-12-16 at 09 58 13

Screenshot 2019-12-16 at 09 58 02

### Steps to reproduce

Delegates tab -> Voted
Wallet -> Votes

### Which version(s) does this affect? (Environment, OS, etc...)

1.23.0

### PR DESCRIPTION
**Pull request by reyraa**
### What issue have I solved?

Resolves #2704 

### How have I implemented/fixed it?
- Used the same illustrations and wording as in transactions tab.
Additionally, added the missing dark mode icons for the top bar as per Domenico's request. 

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/screens/wallet/transactions/transactionsList.js [hunk 1]
```diff
@@ -93,6 +93,7 @@ class TransactionsList extends React.Component {
           : (
             <EmptyState className={styles.emptyState}>
               <Illustration name="emptyWallet" />
+              <h3>{t('No transactions found.')}</h3>
```
Comment (slaweet) [inline src/components/screens/wallet/transactions/transactionsList.js]: Not having a message in empty transactions was according to the design https://projects.invisionapp.com/d/main?origin=v7#/console/17570736/365248392/preview?scrollOffset=518 as there already is a message in the empty chart box.

should it really be changed?

Comment (reyraa) [reply src/components/screens/wallet/transactions/transactionsList.js]: As mentioned, requested by the designer.

Comment (reyraa) [reply src/components/screens/wallet/transactions/transactionsList.js]: Though I agree, it was inconsistent.
