### PR TITLE
Fix issues with request token

### LINKED ISSUE #4737: Issues with Request token
### Expected behavior
- Recipient chain selection should render the chain logo and name
- token selection should render the right token values and logo
- Request token link should open the send form when visited

### Actual behavior

- Recipient chain selection don’t render the chain logo and name
Recipient Application

- Token selection renders wrong token values (this should be gotten from the useTransferableTokens hook)
+ Add message (Optional)

- On redirecting to the request link generated , the send token modal doesn’t open

### Steps to reproduce
- Visit the wallet page
- Click on the request button
- above issues raised should be observable

### Which version(s) does this affect? (Environment, OS, etc...)
all

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4737 

### How was it solved?

- [x] Refactor `Request`` component from class to function
- [x] Consume `useTransferableTokens` hook to get list of tokens
- [x] Consume `useApplicationExplore` hook to get list of chains
- [x] Fix composed shareable link
- [x] Fix SendForm to work with generated request link
- [x] Update unit tests

### How was it tested?

- jest
- visually

### CODE REVIEW

File: src/modules/wallet/components/request/request.js [hunk 1]
```diff
@@ -32,61 +61,41 @@ const Account = () => {
...
+      metadata: { address },
+    },
+  ] = useCurrentAccount();
+
+  const { t } = useTranslation();
+  const [state, dispatch] = useReducer(
+    (stateData, value) => ({ ...stateData, ...value }),
+    requestInitState
+  );
+  const timeout = useRef({
```
Comment (oskarleonard) [inline src/modules/wallet/components/request/request.js]: This seems to be dead code right now? What do we do with it?

File: src/modules/wallet/components/request/request.js [hunk 2]
```diff
@@ -1,21 +1,50 @@
...
+  },
+  token: {
+    error: false,
+    value: '',
+    loading: false,
+    feedback: '',
+  },
+  recipientChain: {
+    error: false,
+    value: '',
```
Comment (oskarleonard) [inline src/modules/wallet/components/request/request.js]: Would be nice if type of value wasnt mixed in the requestInitState. From the glance of it it looks like 
recipientChain.value represents a string holder but is in fact an object. So either 
`value: {},`
or
`value: undefined,`
would make more sense imo

File: src/modules/wallet/components/request/request.js [hunk 3]
```diff
@@ -32,61 +61,41 @@ const Account = () => {
...
+    (stateData, value) => ({ ...stateData, ...value }),
+    requestInitState
+  );
+  const timeout = useRef({
+    amount: null,
+    reference: null,
+  });
+
+  const { applications } = useApplicationExploreAndMetaData();
+  const { data: tokens } = useTransferableTokens(state.recipientChain.value);
```
Comment (oskarleonard) [inline src/modules/wallet/components/request/request.js:77]: Now when we use this as a hook this will produce RQ cache side effect when typing amount before selecting an application. RQ will cache a wrong client in `useTransferableTokens`... So we need to extend our `useTokensSupported` hook to include an enabled option and use like this 

```
  } = useTokensSupported({
    client: client.current,
    options: { enabled: !!application?.serviceURLs?.[0] },
  });
  ```

Comment (oskarleonard) [reply src/modules/wallet/components/request/request.js:77]: image

To prevent this race condition with RQ

**Review by ikem-legend — APPROVED** [review]

**Review by oskarleonard — APPROVED** [review]
