### PR TITLE
 Fix monitor to work for Custom mainnet/testnet nodes - Closes #2664

### LINKED ISSUE #2664: Monitor with mainnet/testnet custom node stopped working
### Steps to reproduce

1. Set custom node, which is actually on testnet or mainnet (based on `nethash`)  Screenshot 2019-11-22 at 13 07 12
2. Go to Monitor

### Expected behavior
See data:
Screenshot 2019-11-22 at 13 03 42

### Actual behavior
See message that monitor is not available:
Screenshot 2019-11-22 at 13 05 38

### Which version(s) does this affect? (Environment, OS, etc...)
Current `development` branch after merging https://github.com/LiskHQ/lisk-desktop/pull/2640

### PR DESCRIPTION
**Pull request by slaweet**
### What issue have I solved?

Resolves #2664

### How have I implemented/fixed it?

Updated the monitor pages to reuse logic from `liskService.js` to check if lisk service is available or not. It is using `getNetworkNameBasedOnNethash`.

### How has this been tested?

Follow steps to reproduce in #2664

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/utils/api/lsk/liskService.js [hunk 1]
```diff
@@ -125,6 +125,14 @@ const liskServiceApi = {
...
   },
 
+  getLiskServiceUrl: (networkConfig) => {
+    try {
+      return getServerUrl(networkConfig);
+    } catch (e) {
+      return null;
+    }
+  },
+
```
Comment (reyraa) [inline src/utils/api/lsk/liskService.js]: My comment is not limited to this particular method, but documenting inputs and outputs is recommended habit because it helps other developers to know what to pass and what to expect. even for testing, it makes the review process easier.
In addition, can we make sure the output of the function has a unique type. in this case we don't need to perform complex checks when using the output in conditional statements.

Comment (slaweet) [reply src/utils/api/lsk/liskService.js]: I added jsDoc to this function. Please check it and let me know what you think.

Comment (reyraa) [reply src/utils/api/lsk/liskService.js]: Looks good. Thanks
