### PR TITLE
Retain form values and fix unlock feature bug

### LINKED ISSUE #4699: Form input values are not retained while navigating back
### Expected behavior

All types of transaction should hold the input values when a user navigates `back` and `continue` during transaction submission.

### Actual behavior

Input values are cleared while navigates `back` and `continue` during transaction submission.

### Steps to reproduce

- Try to send token transfer/multisignature registration  and navigate back after transaction summary

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #4699, #4597  

### How was it solved?

- Retain form values when navigated back to previous step

### How was it tested?

- Updated tests
- Tested manually

### CODE REVIEW

File: src/modules/pos/validator/components/SentStakes/SentStakes.js [hunk 1]
```diff
@@ -60,10 +60,10 @@ const SentStakes = ({ history }) => {
         </Heading>
       </BoxHeader>
       <BoxContent>
-        <QueryTable
+        <Table
```
Comment (soroushm) [inline src/modules/pos/validator/components/SentStakes/SentStakes.js]: whats the reason to change query table to the table ?

Comment (ManuGowda) [reply src/modules/pos/validator/components/SentStakes/SentStakes.js]: At max one can have 10 stakes, not beyond that, so we just need table for this scenario.

Comment (oskarleonard) [reply src/modules/pos/validator/components/SentStakes/SentStakes.js]: I guess it is the loadmore button you want to fix with this? 
The root cause of that is that `useSentStakes` uses `useCustomInfiniteQuery` instead of `useCustomQuery`, i have a refactored that in my branch.

**Review by oskarleonard — DISMISSED** [review]

**Review by oskarleonard — DISMISSED** [review]

**Review by eniolam1000752 — DISMISSED** [review]

File: src/modules/pos/validator/components/SentStakes/SentStakes.js (hunk 1 above)
Comment (soroushm) [reply src/modules/pos/validator/components/SentStakes/SentStakes.js]: please revert the changes, the hook should useCustomQuery its alrady taking care by oscar, if that one is changed the update button will removed at the same queryTable lets app stay consistent

**Review by soroushm — APPROVED** [review]

**Review by oskarleonard — APPROVED** [review]
