### PR TITLE
fix max blocks forged numbers and time

### LINKED ISSUE #3002: Incorrect round status in delegates monitoring page
### Expected behavior
In delegates page, the round status should show XX/101. 

### Actual behavior
Round status is showing XX/103 which is incorrect. We forge 101 blocks per cycle.

### Which version(s) does this affect? (Environment, OS, etc...)
1.27.0

### PR DESCRIPTION
**Pull request by UsamaHameed**
### What was the problem?
This PR resolves #3002 

### How was it solved?
Fix the hardcoded values

### How was it tested?
NA

### CODE REVIEW

File: src/constants/delegates.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+// eslint-disable-next-line import/prefer-default-export
+export const MAX_BLOCKS_FORGED = 101;
```
Comment (MichalTuleja) [inline src/constants/delegates.js:2]: This is correct for the version 3 of Lisk Core. The v4 and the v5 are going to forge 103 blocks per round.

Comment (UsamaHameed) [reply src/constants/delegates.js:2]: I think yes. We are going to change this constant again when we start using lisk core v4. As far as I know, there is no api that returns this number.

Comment (MichalTuleja) [reply src/constants/delegates.js:2]: That's true, there is no API for that. It can be hardcoded for now, but Lisk Service can provide that value in the future.
