### PR TITLE
Fix zero fee balance issue

### LINKED ISSUE #5443: Fee error while sending a transaction from sidechain to mainchain
### Expected behavior
There shouldn't be any errors when calculating the fee
### Actual behavior
There's an error when trying to calculate the fee
image

### Steps to reproduce
Try sending LSK from Bloclite to 'Mainchain', on the current testnet
### Which version(s) does this affect? (Environment, OS, etc...)
Desktop 3.0.0-rc.3

This could also be a Lisk Service issue, not sure.

### LINKED ISSUE #5445: Fee error while sending a transaction from sidechain to mainchain
### Expected behavior

Lisk service will handle the insufficient fee error in back.

As a backup approach Call Fee estimate endpoint once knowing there is enough balance to cover the transaction fee.

### Actual behavior

There's an error when trying to calculate the fee
image

### Steps to reproduce

Try sending LSK from Bloclite to 'Mainchain', on the current testnet

### Which version(s) does this affect? (Environment, OS, etc...)
Desktop 3.0.0-rc.3

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #5445 

### How was it solved?

- [x] Implement a hook to validate fee balance
- [x] Apply hook to all transaction use case
- [x] Write unit tests

### CODE REVIEW

File: src/modules/account/components/AccountMenuListing/AccountMenuListing.js [hunk 1]
```diff
@@ -33,6 +40,22 @@ const AccountMenuListing = ({ className, onItemClicked }) => {
     return { component, data };
   }
 
+  const getInSuffienctBalanceMessage = () => {
```
Comment (oskarleonard) [inline src/modules/account/components/AccountMenuListing/AccountMenuListing.js]: Spelling of Sufficient for this function globally

File: src/modules/pos/validator/components/SentStakes/SentStakes.js [hunk 2]
```diff
@@ -31,12 +32,26 @@ function useStakerAddress(searchParam) {
 function ClaimRewardsDialogButton({ address }) {
   const { t } = useTranslation();
   const { data: rewardsClaimable } = useRewardsClaimable({ config: { params: { address } } });
+  const { hasSufficientBalanceForFee, feeToken } = useValidateFeeBalance();
+
+  const getInSuffienctBalanceMessage = () => {
+    if (!hasSufficientBalanceForFee) {
```
Comment (oskarleonard) [inline src/modules/pos/validator/components/SentStakes/SentStakes.js]: Why doesnt this require `(!hasAvailableTokenBalance)` as well?

File: src/modules/pos/validator/components/ValidatorsMonitorView/Validators.js [hunk 3]
```diff
@@ -32,6 +33,27 @@ import styles from './Validators.css';
...
+  const hasTokenBalances = tokenBalances.data?.data?.some(
+    ({ availableBalance }) => !!BigInt(availableBalance)
+  );
+
+  const { hasSufficientBalanceForFee, feeToken } = useValidateFeeBalance();
+
+  const getInSuffienctBalanceMessage = () => {
+    if (!hasTokenBalances) {
+      return {
+        message: t('Token balance is not enough to stake a validator.'),
```
Comment (oskarleonard) [inline src/modules/pos/validator/components/ValidatorsMonitorView/Validators.js]: Cant we abstract these messages somehow. A lot of duplication  of `if (!hasSufficientBalanceForFee) {`,  `if (!hasTokenBalances) {` varies slightly between components. But feels like it could be abstracted to a hook `useInSufficientBalanceMessage(noTokenBalanceSuffix)` or we can use a const `IN_SUFFICIENT_BALANCE_MESSAGES = {...}`

`const data = useInSufficientBalanceMessage('to stake a validator.')`
Or we can pass in domain 🤔 
`const data = useInSufficientBalanceMessage(VALIDATOR)`

File: src/modules/pos/validator/components/SentStakes/SentStakes.js (hunk 2 above)
Comment (eniolam1000752) [reply src/modules/pos/validator/components/SentStakes/SentStakes.js]: For this, they don't require it because the only debit value incurred by the customer when claiming a reward or unlocking a token is the fee not the token balance of the user

**Review by oskarleonard — DISMISSED** [review]

File: src/modules/common/constants.js [hunk 4]
```diff
@@ -107,3 +108,11 @@ export const INFO_BANNERS = {
     infoLinkText: 'Explore',
   },
 };
+
+export const INSUFFICENT_TOKEN_BALANCE_MESSAGE = {
+  registerMultiSignature: i18next.t(
+    'Token balance is not enough to register a multisignature account.'
+  ),
+  registerValidator: i18next.t('Token balance is not enough to register a validator profile'),
```
Comment (ManuGowda) [inline src/modules/common/constants.js]:
```suggestion
  registerValidator: i18next.t('Token balance is not enough to register a validator profile.'),
```

File: src/locales/en/common.json [hunk 5]
```diff
@@ -711,7 +711,7 @@
   "Token": "Token",
   "Token balance": "Token balance",
   "Token balance is not enough to register a multisignature account.": "Token balance is not enough to register a multisignature account.",
-  "Token balance is not enough to register a validator.": "Token balance is not enough to register a validator.",
+  "Token balance is not enough to register a validator profile": "Token balance is not enough to register a validator profile",
```
Comment (ManuGowda) [inline src/locales/en/common.json]:
```suggestion
  "Token balance is not enough to register a validator profile.": "Token balance is not enough to register a validator profile.",
```

File: src/locales/en/common.json [hunk 6]
```diff
@@ -679,11 +679,11 @@
   "There are no results matching your search term.": "There are no results matching your search term.",
   "There are no stakes in queue, please select validators to stake.": "There are no stakes in queue, please select validators to stake.",
   "There are no tokens to display for this account at this moment.": "There are no tokens to display for this account at this moment.",
-  "There are no tokens to send at this moment.": "There are no tokens to send at this moment.",
   "There are no transactions for this account.": "There are no transactions for this account.",
   "There are no transactions for this block.": "There are no transactions for this block.",
   "There are no transactions for this chain.": "There are no transactions for this chain.",
   "There are no transactions requested from Lisk Desktop yet.": "There are no transactions requested from Lisk Desktop yet.",
+  "There are no {{feeTokenSymbol}} tokens to pay for fees": "There are no {{feeTokenSymbol}} tokens to pay for fees",
```
Comment (eniolam1000752) [inline src/locales/en/common.json]:
```suggestion
  "There are no {{feeTokenSymbol}} tokens to pay for fees.": "There are no {{feeTokenSymbol}} tokens to pay for fees.",
```

File: src/locales/en/common.json (hunk 5 above)
Comment (eniolam1000752) [inline src/locales/en/common.json]:
```suggestion
  "Token balance is not enough to register a validator profile.": "Token balance is not enough to register a validator profile.",
```

**Review by oskarleonard — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
