### PR TITLE
Fix the reclaim transaction success status screen crash issue - Closes #4127 

### LINKED ISSUE #4127: Reclaim transaction success status screen crashes
### Expected behavior

Should display screen and redirect to wallet when button is clicked

### Actual behavior

App crashes (evendo transaction success) because button is not defined in templates `className={`${styles.btn} ${template.button.className}`}` `src/components/screens/reclaim/modal/status/status.js`

### Steps to reproduce

- Login with legacy account
- Add balance if need
- Submit the transaction

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.0-linux

Screenshot from 2022-01-31 14-11-14
Screenshot from 2022-01-31 14-10-45

### PR DESCRIPTION
**Pull request by reyraa**
### What was the problem?

This PR resolves #4127

### How was it solved?

- Simplified the view
- Added custom message
- Blocked users from closing the modal

### How was it tested?

- Updated uni tests
- Reclaimed several accounts to test it

### CODE REVIEW

File: src/components/screens/reclaimBalance/modal/status/statusMessages.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+/* istanbul ignore file */
+import { statusMessages } from '@shared/transactionResult/statusConfig';
+import { txStatusTypes } from '@constants';
+
+const registerDelegatesMessages = t => ({
```
Comment (isalga) [inline src/components/screens/reclaimBalance/modal/status/statusMessages.js:5]: Please rename constant correctly

File: src/components/screens/reclaimBalance/modal/status/status.test.js [hunk 2]
```diff
@@ -80,12 +78,11 @@ describe('Status', () => {
 
     const wrapper = shallow(<Status {...propsWithError} />);
     expect(wrapper.find('.status-container')).toExist();
-    expect(wrapper.find(FailAction)).toExist();
     expect(wrapper.find(TransactionResult).props()).toMatchObject({
       illustration: 'default',
       status: { code: 'BROADCAST_ERROR', message: JSON.stringify({ message: 'error:test' }) },
       title: 'Transaction failed',
-      className: 'content false',
+      className: 'content',
```
Comment (isalga) [inline src/components/screens/reclaimBalance/modal/status/status.test.js:85]: Can you add the rest of the text of the screen to text? I suspect error message is not passed.

**Review by isalga — CHANGES_REQUESTED** [review]

File: src/components/screens/reclaimBalance/modal/status/status.test.js (hunk 2 above)
Comment (reyraa) [reply src/components/screens/reclaimBalance/modal/status/status.test.js:85]: I do not pass the error. The `TransactionResult` component reads it from the Redux store.

**Review by ManuGowda — APPROVED** [review]

**Review by isalga — APPROVED** [review]
