### PR TITLE
Bugfix pom and validator domain

### LINKED ISSUE #5319: Sign multisignature issues
### Expected behavior

1. `Please paste the JSON here` should allow users to past the JSON
2. The border issue should be resolved
 
### Actual behavior

1. `Please paste the JSON here` doesn't allow you to paste the JSON, insted it opens up the read files.
2. Screenshot 2023-09-15 at 9 50 34 AM 

### Steps to reproduce
Design [link](https://www.figma.com/file/KcrDpvWEKQhdGwNd4CZ5NY/Desktop-Prototype?type=design&node-id=71%3A75707&mode=design&t=GwJdL2kQmBaW3dTD-1)

1. Select `Sign multisignature`
2. Copy a valid JSON data
3. Try to paste, and observe the read file dialog opens

### LINKED ISSUE #5321: Banned delegate profile page doesn't work
### Actual behavior

banned_delegates

Desktop 3.0.0-rc.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5319, #5321, #5320, #5322 and #5323

### How was it solved?

- Handle the pom edge case with null check
- Ensure staking validator is disabled when a validator is banned
- Updated outdated blog post links

#### Additional improvements

- Restrict window actions (copy, paste, cut, etc..) to prevent hijacking password

### How was it tested?

- For all issues a screen recoding has been attached, so we can refer them for validation
- The commits are also atomic so please review them based on commit fix

### CODE REVIEW

File: src/modules/common/components/uploadJSONInput/uploadJSONInput.js [hunk 1]
```diff
@@ -42,13 +42,11 @@ const UploadJSONInput = ({
     accept: {
       'application/JSON': ['.json'],
     },
+    noClick: true,
```
Comment (oskarleonard) [inline src/modules/common/components/uploadJSONInput/uploadJSONInput.js:45]: Why did we remove this feature? I cannot see it in any issue nor description 🤔 

Clicks are more useful than drag and drop imo, especially since users see what files are accepted easily
image

Comment (oskarleonard) [reply src/modules/common/components/uploadJSONInput/uploadJSONInput.js:45]: Ah, never mind, i see we still have 
`Restore from JSON file` which users can click

Comment (oskarleonard) [reply src/modules/common/components/uploadJSONInput/uploadJSONInput.js:45]: **But feels like the text of these should be more similar.**

**Add account also allows for paste now (so we should probably remove the `placeholderText` here?)**
And maybe change the title from Restore from JSON file to Select JSON file 🤔 
image

___________________

**The header above the drag and drop here feels strange.**
1 header with 2 actions. Maybe remove the `prefixLabel` and make it just say "Select JSON file with transaction value"
image

File: src/modules/common/hooks/useFilter.js [hunk 2]
```diff
@@ -42,6 +42,10 @@ export default function useFilter(defaultFilters = {}) {
     [filters]
   );
 
+  useEffect(() => {
+    setFilters(inputFilters);
```
Comment (oskarleonard) [inline src/modules/common/hooks/useFilter.js:46]: **Syncing** props and state is usually an anti-pattern. 
It is OK though to **initialise** the state but not trying to keep them the sync since it leads to multiple sources of truth. Which probably was why the props name initially was `defaultFilters` (`initialFilters` would be fine too).

We need to test this thoroughly.

Comment (oskarleonard) [reply src/modules/common/hooks/useFilter.js:46]: Dont know if it is related to the ani pattern but going to http://0.0.0.0:8080/#/wallet now crashes the app 
image

Comment (ManuGowda) [reply src/modules/common/hooks/useFilter.js:46]: Yes I dint like this fix, probably we can discuss a better fix as we know the problem

Comment (oskarleonard) [reply src/modules/common/hooks/useFilter.js:46]: What i did was playing around with the filters on different pages then going to /wallet. Cannot replicate this though, so it might be working. But please also make such sanity check 🙃

File: src/modules/common/components/uploadJSONInput/uploadJSONInput.test.js [hunk 3]
```diff
@@ -82,7 +82,7 @@ describe('Upload JSON input component', () => {
 
     render(<UploadJSONInput {...props} />);
 
-    const inputNode = screen.getByLabelText('Restore from JSON file');
+    const inputNode = screen.getByLabelText('Select transaction JSON file');
```
Comment (ManuGowda) [inline src/modules/common/components/uploadJSONInput/uploadJSONInput.test.js]:
```suggestion
    const inputNode = screen.getByLabelText(props.label);
```

File: src/modules/common/components/uploadJSONInput/uploadJSONInput.test.js [hunk 4]
```diff
@@ -98,7 +98,7 @@ describe('Upload JSON input component', () => {
 
     const invalidJson = '{"result":true, "count":42';
     const file = new File([invalidJson], 'file.json', { type: 'application/json' });
-    const inputNode = screen.getByLabelText('Restore from JSON file');
+    const inputNode = screen.getByLabelText('Select transaction JSON file');
```
Comment (ManuGowda) [inline src/modules/common/components/uploadJSONInput/uploadJSONInput.test.js]:
```suggestion
    const inputNode = screen.getByLabelText(props.label);
```

File: src/modules/auth/hooks/useRestrictWindowActions.js [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+
+export const useRestrictWindowActions = ({ actions, window }) => {
+  const restrictAction = useCallback((event) => {
+    event.preventDefault();
+  }, []);
+
+  useEffect(() => {
+    actions?.forEach((action) => action && window.addEventListener(action, restrictAction));
+    return () => {
+      actions?.forEach((action) => action && window?.removeEventListener(action, restrictAction));
```
Comment (ikem-legend) [inline src/modules/auth/hooks/useRestrictWindowActions.js]: I feel like `window` would still exist when the hook is unmounted, hence no need for the optional chaining, but other than that the hook works as expected

**Review by oskarleonard — DISMISSED** [review]

File: src/modules/auth/components/EnterPasswordForm/EnterPasswordForm.js [hunk 6]
```diff
@@ -9,6 +9,7 @@ import Box from 'src/theme/box';
 import BoxContent from 'src/theme/box/content';
 import { PrimaryButton, TertiaryButton } from 'src/theme/buttons';
 import styles from './EnterPasswordForm.css';
+import { useRestrictWindowActions } from '../../hooks/useRestrictWindowActions';
```
Comment (oskarleonard) [inline src/modules/auth/components/EnterPasswordForm/EnterPasswordForm.js]: alias

File: src/modules/auth/hooks/useRestrictWindowActions.js [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+    event.preventDefault();
+  }, []);
+
+  useEffect(() => {
+    actions?.forEach((action) => action && window.addEventListener(action, restrictAction));
+    return () => {
+      actions?.forEach((action) => action && window.removeEventListener(action, restrictAction));
+    };
+  }, [actions, window, restrictAction]);
+};
```
Comment (eniolam1000752) [inline src/modules/auth/hooks/useRestrictWindowActions.js]: do we need to pass in window as an argument to the hook?. Since `window` is a global variable and available any where we should be able to get it in the hook without passing it to the hook right ?

**Review by ikem-legend — DISMISSED** [review]

File: src/modules/wallet/components/overview/overview.js [hunk 8]
```diff
@@ -80,7 +80,7 @@ const Overview = ({ isWalletRoute, history }) => {
         isBanned,
         pomHeight: pomHeights ? pomHeights[pomHeights.length - 1] : 0,
         readMore: () => {
-          const url = 'https://lisk.com/blog/development/lisk-staking-process';
+          const url = 'https://lisk.com/blog/posts/lisk-staking-process';
```
Comment (eniolam1000752) [inline src/modules/wallet/components/overview/overview.js:83]: can't we have this in a .env file  just as we do for the environment variable, PRODUCTION or DEBUG

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]

File: src/modules/wallet/components/overview/overview.js (hunk 8 above)
Comment (ManuGowda) [reply src/modules/wallet/components/overview/overview.js:83]: this was a category change.. in website they changed the category of research, development, posts, etc.. so this is just a one time thing.

**Review by oskarleonard — APPROVED** [review]

**Review by eniolam1000752 — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]
