### PR TITLE
Refactor send form to fix max amount - Closes #2659

### LINKED ISSUE #2659: BTC transfer doesn't work
### Description
i am using mac os. trying to send bitcoin from bitcoin wallet. on the transaction summary page when i click on the send button (bitcoin wallet) nothing happens. 

### Expected behavior
I would expect transaction confirmed screen

### Actual behavior  
nothing happend when send bitcoin button clicked

### Steps to reproduce
Follow the send bitcoin process in lisk desktop

### Which version(s) does this affect? (Environment, OS, etc...)
Both maOS and Windows

### PR DESCRIPTION
**Pull request by slaweet**
### What issue have I solved?

Resolves #2659

### How have I implemented/fixed it?

- [x] Create and use `useAmountField` react hook
- [x] Create and use `useRecipientField` react hook
- [x] Create and use `useProcessingSpeed` react hook
- [x] Create and use `useMessage` react hook
- [x] Move amount and recipient state from `FormBase` to `FormBTC` and `FormBTC` component
- [x] Remove duplicate `amount` state from `FormBTC`
- [x] Move `dynamicFees` and `dynamicFeesRetrieved` to `useProcessingSpeed` hook
- [x] Ensure Send entire balance works with BTC
- [x] ~Remove 300 ms delay in send form amount validation"~ - I reverted this in the end, it caused e2e tests of send to fail randomly due to a race condition in recipient field not being updated before going to the next step.

### How has this been tested?

Try to send LSK and BTC with various options (including max amount)

Note how the refactoring eliminated big files over 200 lines and also slightly reducing total lines of code:

before:

```
$ wc -l src/components/screens/wallet/send/form/*.js | sort -n
   14 src/components/screens/wallet/send/form/form.js
   20 src/components/screens/wallet/send/form/index.js
  103 src/components/screens/wallet/send/form/formLsk.js
  106 src/components/screens/wallet/send/form/formBtc.test.js
  124 src/components/screens/wallet/send/form/bookmarkAutoSuggest.js
  188 src/components/screens/wallet/send/form/formBtc.js
  200 src/components/screens/wallet/send/form/form.test.js
  236 src/components/screens/wallet/send/form/formBase.js
  991 total
```

after:

```
$ wc -l src/components/screens/wallet/send/form/*.js | sort -n
      14 src/components/screens/wallet/send/form/index.js
      23 src/components/screens/wallet/send/form/useRecipientField.js
      25 src/components/screens/wallet/send/form/form.js
      28 src/components/screens/wallet/send/form/useDynamicFeeCalculation.js
      28 src/components/screens/wallet/send/form/useMessageField.js
      49 src/components/screens/wallet/send/form/useProcessingSpeed.js
      63 src/components/screens/wallet/send/form/formBase.js
      63 src/components/screens/wallet/send/form/useAmountField.js
      82 src/components/screens/wallet/send/form/formLsk.js
      85 src/components/screens/wallet/send/form/amountField.js
      96 src/components/screens/wallet/send/form/formBtc.test.js
      98 src/components/screens/wallet/send/form/formBtc.js
     124 src/components/screens/wallet/send/form/bookmarkAutoSuggest.js
     199 src/components/screens/wallet/send/form/form.test.js
     977 total
```

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-desktop/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-desktop/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

File: src/components/screens/wallet/send/form/useProcessingSpeed.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+const useProcessingSpeed = () => {
+  const { t } = useTranslation();
+
+  const dispatch = useDispatch();
+  const { dynamicFees } = useSelector(state => state.service);
+  useEffect(() => {
+    dispatch(dynamicFeesRetrieved());
+  }, []);
+  const isLoading = Object.keys(dynamicFees).length === 0;
```
Comment (reyraa) [inline src/components/screens/wallet/send/form/useProcessingSpeed.js]: The catch is not handled properly and this always stays in loading if the API call fails.

File: src/components/screens/wallet/send/form/index.js [hunk 2]
```diff
@@ -1,20 +1,14 @@
...
-  dynamicFees: state.service.dynamicFees,
   networkConfig: state.network,
 });
 
-const mapDispatchToProps = {
-  dynamicFeesRetrieved,
-};
-
-export default connect(mapStateToProps, mapDispatchToProps)(withTranslation()(Form));
+export default connect(mapStateToProps)(withTranslation()(Form));
```
[the remark this answers is not in the document]
Comment (slaweet) [reply src/components/screens/wallet/send/form/index.js]: This would require a lot of changes to the tests. As now the approach is to mount the component without the HOCs. 

There are several different ways how to handle the tests https://stackoverflow.com/questions/56827300/how-to-test-a-component-using-react-redux-hooks

IMO We should have an STM to chose one approach and update our testing guide accordingly. IMO there's a lot to do and thus I suggest this topic is outside the scope of this PR.

[the remark this answers is not in the document]
Comment (reyraa) [reply src/components/screens/wallet/send/form/index.js]: Good point. We can do this later.

**Comment by slaweet** [comment]
Thank you for the feedback @reyraa.

I made changes to address your comments.

The only one I didn't do anything about is

> You have increased the number of renders of FormLsk and FormBtc (including their children) by a factor of over 3.

What do you mean exactly?

I was compering this on FormBtc and number of renders was same or better. Here is an overview of how many renders I got in the following situations:

|                          	| this branch 	| development 	|
|--------------------------	|:-----------:	|------------:	|
| initial page load        	|      6      	|      7      	|
| change 1 digit of amount 	|      2      	|      4      	|
| send entire balance      	|      2      	|      4      	|
| change fee               	|      1      	|      1      	|

File: package.json [hunk 3]
```diff
@@ -106,6 +106,7 @@
     "react-router-dom": "5.0.1",
     "react-swipe": "6.0.3",
     "react-toolbox": "2.0.0-beta.12",
+    "react-use-promise": "0.2.0",
```
Comment (yasharAyari) [inline package.json]: Because we use the latest version of React in our project, you can use react `suspense` instead of `react-use-promise. you can find more information on the below link.
https://reactjs.org/docs/concurrent-mode-suspense.html#what-is-suspense-exactly

Comment (slaweet) [reply package.json]: I don't think we should use `Suspense` as the link you posted describes it as experimental and not stable:

> This page describes experimental features that are not yet available in a stable release. Don’t rely on experimental builds of React in production apps
