### PR TITLE
Fix transaction creation and signing process - Closes #4506

### LINKED ISSUE #4506: Fix remainig issues with the transaction creation and signing process
### Description
We have reinstated the transaction creation process. Due to a number of missing data and features from Lisk Elements, and in order to get the first batch of fixes merged, we'll add the remaining issues here to fix them in a separated ticket.

### Issues
- Review and ensure `getNumberOfSignatures` calculates correctly. Update function arguments.
- Review and update (if needed) the parameters passed to `signMultiSignatureTransactionWithPrivateKey`.
- Remove moduleCommand from the arguments of desktopTxToElementsTx and other params conversion methods.
- Fix multisignature tx signing summary view
   - Fetch the schemas on demand
   - Update the calculation of member signatures
   - Update the calculation of signature status
- Since the sender should sign the tx the last, we should update the conditions of displaying the send button.
- Address these comments https://github.com/LiskHQ/lisk-desktop/pull/4491#pullrequestreview-1137724893

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #4506, #4497

### How was it solved?

- [x] Each command form to pass formProps and commandParams
- [x] Remove unwanted conversions and use lisk-codec for encoding and decoding
- [x] Refactor transaction signing from a regular account for the following transaction types
  - [x] vote
  - [x] delegate registration
  - [x] send token
  - [x] reclaim
- [x] Refactor Register multi-signature flow
- [x] Refactor sign transaction from a multi-signature account on the following transaction types
  - [x] vote
  - [x] delegate registration
  - [x] send token
- [x] Fix summary page UI on register multi-signature account

### How was it tested?

- [x] Update unit test
- [x] Manually test all types of transactions

### CODE REVIEW

File: setup/react/app/index.js [hunk 1]
```diff
@@ -54,6 +54,8 @@ const App = ({ history }) => {
     dispatch(bookmarksRetrieved());
     dispatch(settingsRetrieved());
     dispatch(watchListRetrieved());
+    // Initialize client on first render to get default application
+    client.create({ http: 'http://165.227.246.146:9901', ws: 'http://165.227.246.146:9901' });
```
Comment (ikem-legend) [inline setup/react/app/index.js]: @eniolam1000752 This is a duplicate of some lines above

File: src/modules/dpos/validator/components/RegisterDelegateStatus/index.js [hunk 2]
```diff
@@ -1,13 +1,20 @@
 /* istanbul ignore file */
 import { connect } from 'react-redux';
 import { selectActiveTokenAccount } from 'src/redux/selectors';
+
```
Comment (ikem-legend) [inline src/modules/dpos/validator/components/RegisterDelegateStatus/index.js]: @eniolam1000752 Please remove empty line

File: src/modules/transaction/api/index.js [hunk 3]
```diff
@@ -210,53 +213,48 @@ export const getTransactionBaseFees = network =>
...
   });
 
   // tie breaker is only meant for medium and high processing speeds
-  const tieBreaker = selectedPriority.selectedIndex === 0
-    ? 0 : (MIN_FEE_PER_BYTE * feePerByte * Math.random());
-
-  const size = transactions.getBytes(transactionObject, schema).length;
+  const tieBreaker =
+    selectedPriority.selectedIndex === 0 ? 0 : MIN_FEE_PER_BYTE * feePerByte * Math.random();
+  console.log('>>> parfam', transactionObject, paramsSchema);
```
Comment (ikem-legend) [inline src/modules/transaction/api/index.js]: @eniolam1000752 Please remove console log

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js [hunk 4]
```diff
@@ -1,95 +1,148 @@
 import React, { useEffect } from 'react';
-import { signatureCollectionStatus } from '@transaction/configuration/txStatus';
+import { useDispatch } from 'react-redux';
+// import { signatureCollectionStatus } from '@transaction/configuration/txStatus';
```
Comment (ikem-legend) [inline src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js]: @eniolam1000752 Please remove this and related uses if it's no longer in use

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js [hunk 5]
```diff
@@ -1,95 +1,148 @@
...
+     */
+
     /**
      * All multisignature transactions get signed using a unique action
      * Therefore there's no need to pass the action function, instead the
      * sender account is required.
-     * 
-     * @todo add test coverage for the multisigTransactionSigned action when the signature
-     * collection process is refactored #4506 
+     * CHECK IF SENDER ACCOUNT IS A MULTISIG
```
Comment (ikem-legend) [inline src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js:61]: @eniolam1000752 I don't think comments should be in all caps

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js [hunk 6]
```diff
@@ -1,95 +1,148 @@
...
+  const [sender] = useCurrentAccount();
+  const { moduleCommandSchemas } = useCommandSchema();
 
+  // here, we want to get the auth account details of the user presently wanting to sign the transaction
+  const { data: account, isLoading: isGettingAuthData } = useAuth({
+    config: { params: { address: sender.metadata.address } },
+  });
+
+  // here, we want to get the auth account details of the account that initated the transaction.
+  const { isLoading: isGettingTxInitatorAccount, txInitatorAccount } = useTxInitatorAccount({
```
Comment (ikem-legend) [inline src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js]: @eniolam1000752 Please fix typo in `isGettingTxInitatorAccount` and `txInitatorAccount` and related uses

File: src/modules/transaction/components/TxSummarizer/index.test.js [hunk 7]
```diff
@@ -129,8 +140,16 @@ describe('TxSummarizer', () => {
   it('should display details of the transaction', () => {
     const multisigProps = {
       ...props,
-      rawTx: {
-        ...props.rawTx,
+      formProps: {
+        isValid: true,
+        moduleCommand: MODULE_COMMANDS_NAME_MAP.registerMultisignature,
+        composedFees: { 'Initialization Fee': '1 LSK', Transaction: '1 LSK' },
```
Comment (ikem-legend) [inline src/modules/transaction/components/TxSummarizer/index.test.js:146]: @eniolam1000752 Shouldn't this be `Initialization` rather than `Initialization Fee`?

File: src/modules/transaction/configuration/statusConfig.js [hunk 8]
```diff
@@ -1,23 +1,30 @@
+/* eslint-disable complexity */
 import { isEmpty } from 'src/utils/helpers';
 import { txStatusTypes } from '@transaction/configuration/txStatus';
-import { transactionToJSON, getNumberOfSignatures } from '../utils';
+import { transactionToJSON, getNumberOfSignatures, joinModuleAndCommand } from '../utils';
+import { MODULE_COMMANDS_NAME_MAP } from './moduleCommand';
+// import { getMultiSignatureStatus } from 'src/modules/wallet/utils/multiSignatureStatus';
```
Comment (ikem-legend) [inline src/modules/transaction/configuration/statusConfig.js]: @eniolam1000752 Please remove comment if it's no longer in use

File: src/modules/transaction/hooks/useTxInitiatorAccount.js [hunk 9]
```diff
@@ -0,0 +1,26 @@
+import { useMemo } from 'react';
+import { useAuth } from 'src/modules/auth/hooks/queries';
+import { extractAddressFromPublicKey } from 'src/modules/wallet/utils/account';
+
+const useTxInitatorAccount = ({ transactionJSON }) => {
```
Comment (ikem-legend) [inline src/modules/transaction/hooks/useTxInitiatorAccount.js]: @eniolam1000752 Please fix typo in `useTxInitatorAccount`

File: src/modules/wallet/components/TokenCard/TokenCard.js [hunk 10]
```diff
@@ -10,7 +10,7 @@ const liskSymbol = 'LSK';
 
 const TokenCard = ({ lockedBalance, availableBalance, symbol, url, address }) => (
   <div data-testid="token-card" className={styles.wrapper}>
-    <div className={!lockedBalance || symbol.toUpperCase() !== liskSymbol ? styles.vCenter : ''}>
+    <div className={!lockedBalance || symbol && symbol.toUpperCase() !== liskSymbol ? styles.vCenter : ''}>
```
Comment (ikem-legend) [inline src/modules/wallet/components/TokenCard/TokenCard.js]:
```suggestion
    <div className={!lockedBalance || symbol?.toUpperCase() !== liskSymbol ? styles.vCenter : ''}>
```

File: src/modules/wallet/components/overview/overview.js [hunk 11]
```diff
@@ -51,9 +51,9 @@ const Overview = ({ isWalletRoute, history }) => {
 
   const isBanned = delegate.isBanned;
   const pomHeights = delegate.pomHeights;
-  const { end } = pomHeights?.length ? pomHeights[pomHeights.length - 1] : {};
+  // const { end } = pomHeights?.length ? pomHeights[pomHeights.length - 1] : {};
```
Comment (ikem-legend) [inline src/modules/wallet/components/overview/overview.js]: @eniolam1000752 Please remove comment

File: src/modules/wallet/components/signMultisigSummary/summary.js [hunk 12]
```diff
@@ -1,84 +1,86 @@
...
+import useTxInitatorAccount from '@transaction/hooks/useTxInitiatorAccount';
 import TransactionDetailsContext from '@transaction/context/transactionDetailsContext';
 import layoutSchemaStyles from '@transaction/components/TransactionDetails/layoutSchema.css';
 import ProgressBar from '../signMultisigView/progressBar';
-import { showSignButton, getTransactionSignatureStatus } from '../signMultisigView/helpers';
 import { ActionBar, Feedback } from './footer';
 import styles from './styles.css';
+import { useMultiSignatureStatus } from '../../hooks/useMultiSignatureStatus';
 
+// eslint-disable-next-line complexity
```
Comment (ikem-legend) [inline src/modules/wallet/components/signMultisigSummary/summary.js]: @eniolam1000752 This rule might as well be added to the top

File: setup/config/webpack.config.js [hunk 13]
```diff
@@ -43,6 +43,7 @@ const config = {
       crypto: require.resolve('crypto-browserify'),
       stream: require.resolve('stream-browserify'),
       path: require.resolve('path-browserify'),
+      querystring: require.resolve("querystring-es3")
```
Comment (soroushm) [inline setup/config/webpack.config.js:46]: I'm not sure if we need querystring-es3

File: src/modules/transaction/api/index.js [hunk 14]
```diff
@@ -14,14 +14,12 @@ import { validateAddress } from 'src/utils/validators';
...
 import { getDelegates } from '@dpos/validator/api';
 import { httpPaths } from '../configuration';
-import {
-  desktopTxToElementsTx,
-  sign,
-} from '../utils';
+import { sign } from '../utils';
+import { fromTransactionJSON } from '../utils/encoding';
 
 // TODO: Remove this patch once API is integrated
```
Comment (soroushm) [inline src/modules/transaction/api/index.js]: please remove the todo or create an issue for it

File: src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js [hunk 15]
```diff
@@ -1,124 +1,182 @@
...
+// import { useDispatch } from 'react-redux';
 import { TertiaryButton } from 'src/theme/buttons';
+// import { secondPassphraseRemoved } from '@auth/store/action';
+import { useCommandSchema } from '@network/hooks';
 import Icon from 'src/theme/Icon';
-import Box from 'src/theme/box';
-import Illustration from 'src/modules/common/components/illustration';
-import BoxContent from 'src/theme/box/content';
+// import Box from 'src/theme/box';
+// import Illustration from 'src/modules/common/components/illustration';
```
Comment (soroushm) [inline src/modules/transaction/components/TxSignatureCollector/TxSignatureCollector.js]: please remove unused/commented code

**Review by soroushm — COMMENTED** [review]
init

File: setup/config/webpack.config.js (hunk 13 above)
Comment (eniolam1000752) [reply setup/config/webpack.config.js:46]: I had to include it in webpack alias because webpack could not bundle on jenkins this was the erro it throw


```

ERROR in ./node_modules/@liskhq/lisk-cryptography/dist-node/encrypt.js 5:20-42
Module not found: Error: Can't resolve 'querystring' in '/home/lisk/workspace/lisk-desktop_PR-4518/node_modules/@liskhq/lisk-cryptography/dist-node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
	- install 'querystring-es3'
```

File: src/modules/dpos/validator/store/actions/voting.js [hunk 16]
```diff
@@ -68,86 +70,85 @@ export const voteEdited = (data) => async (dispatch) => dispatch({
...
-  } else {
-    dispatch({ type: actionTypes.votesSubmitted });
-    dispatch(timerReset());
+  } catch (exp) {
     dispatch({
-      type: txActionTypes.transactionCreatedSuccess,
-      data: tx,
+      type: actionTypes.votesRetrieved,
+      data: {
+        account: {},
```
Comment (ManuGowda) [inline src/modules/dpos/validator/store/actions/voting.js:117]: the response format doesn't make sense to me, there is no such thing as account. can you cross check what the response format should be?

File: src/modules/token/fungible/store/actions.js [hunk 17]
```diff
@@ -15,19 +15,24 @@ import { createGenericTx } from '@transaction/api/index';
...
   const wallet = selectActiveTokenAccount(state);
-
   const [error, tx] = await to(
-    createGenericTx({
-      transactionObject,
+    signTransaction({
+      transactionJSON,
       wallet,
-      schema: state.network.networks.LSK.moduleCommandSchemas[transactionObject.moduleCommand],
+      schema: moduleCommandSchemas[formProps.moduleCommand],
```
Comment (soroushm) [inline src/modules/token/fungible/store/actions.js:32]: we have exact semilar on transaction/store/action needs to be changed

File: src/modules/legacy/components/Summary/Summary.js [hunk 18]
```diff
@@ -1,45 +1,58 @@
...
+      command,
+      fee: 132000, // @TODO: fee value should be gotten from service
+      signatures: [],
+      nonce: wallet.sequence?.nonce,
+      senderPublicKey: wallet.summary?.publicKey,
+      params: commandParams,
+    }),
+    [wallet.legacy?.balance, module, command, wallet.sequence?.nonce, wallet.summary?.publicKey]
+  );
+  // const { minFee } = useTransactionFeeCalculation({
```
Comment (ManuGowda) [inline src/modules/legacy/components/Summary/Summary.js:37]: why this code commented?

File: src/modules/network/store/reducer.js [hunk 19]
```diff
@@ -52,7 +52,10 @@ const network = (state = initialState, action) => {
           ...state.networks,
           LSK: {
             ...state.networks.LSK,
-            moduleCommandSchemas: action.data.reduce((acc, item) => {
+            schemas: {
+              ...action.data,
```
Comment (ManuGowda) [inline src/modules/network/store/reducer.js:56]: we could have filtered `commands` here, as it will be available below? unnecessarily we will have duplication?

File: src/modules/network/utils/api/index.js [hunk 20]
```diff
@@ -16,12 +16,11 @@ const httpPaths = {
...
-  baseUrl,
-  path: httpPaths.networkStatus,
-});
+export const getNetworkStatus = ({ baseUrl }) =>
+  http({
+    baseUrl,
+    path: httpPaths.networkStatus,
+  });
 
 const getServiceUrl = ({ name, address = 'http://165.227.246.146:9901' }) => {
```
Comment (ManuGowda) [inline src/modules/network/utils/api/index.js:25]: Please add TODO to remove this. By now the metadata endpoint should return the devnet configuration? so I am not sure even if we need this.

File: src/modules/token/fungible/components/SendForm/SendForm.js [hunk 21]
```diff
@@ -134,15 +134,39 @@ const SendForm = (props) => {
...
+      recipient,
+    },
+  };
+
+  let commandParams = {
+    tokenID: token?.tokenID,
+    amount: toRawLsk(amount.value),
+    recipientAddress: recipient.value,
+    data: reference.value,
+    accountInitializationFee: 5000000, // TODO: Replace the initalization fee constant from service endpoint
```
Comment (ManuGowda) [inline src/modules/token/fungible/components/SendForm/SendForm.js:150]: Please create GitHub issue before we forget 🙏🏼

File: src/modules/token/fungible/store/actions.test.js [hunk 22]
```diff
@@ -82,7 +83,7 @@ describe('actions: transactions', () => {
       expect(dispatch).toHaveBeenCalledWith(expectedAction);
     });
 
-    it('should dispatch transactionSignError action if there are errors during transaction creation', async () => {
+    it.skip('should dispatch transactionSignError action if there are errors during transaction creation', async () => {
```
Comment (ManuGowda) [inline src/modules/token/fungible/store/actions.test.js:86]: why is it skipped?

**Review by soroushm — COMMENTED** [review]
look like modulecommand is change in transaction object and vote is complain about it

File: src/modules/transaction/components/Multisignature/Multisignature.js [hunk 23]
```diff
@@ -75,23 +68,30 @@ const Multisignature = ({
...
   account,
   network,
+  moduleCommandSchemas,
 }) => {
   const [copied, setCopied] = useState(false);
 
   const onCopy = () => {
-    copyToClipboard(transactionToJSON(transactions.signedTransaction));
+    const schema = moduleCommandSchemas[joinModuleAndCommand(transactions.signedTransaction)];
+    const jsonParams = codec.codec.toJSON(schema, transactions.signedTransaction.params);
```
Comment (ManuGowda) [inline src/modules/transaction/components/Multisignature/Multisignature.js:77]: You can replace all these logic with `toTransactionJSON` from `encoding.js`?

File: src/modules/transaction/components/Overview/Overview.js [hunk 24]
```diff
@@ -122,8 +122,9 @@ const Overview = () => {
   const [params, setParams] = useState({ limit: 7, interval: 'day' });
   const [activeTab, setActiveTab] = useState('week');
   const colorPalette = getColorPalette(useTheme());
-  // Fallback token for transaction statistics // @TODO: Add selector for active token when available in service
-  const tokenID = '0000000000000000';
+  // Fallback token for transaction statistics
+  // @TODO: Add selector for active token when available in service
```
Comment (ManuGowda) [inline src/modules/transaction/components/Overview/Overview.js:126]: Going forward along with TODOs can please create GitHub issues? and add the link here? so that we know what TODOs we need to address

File: src/modules/transaction/utils/helpers.js [hunk 25]
```diff
@@ -30,11 +30,32 @@ export const getFeeStatus = ({ fee, token, customFee }) => {
...
-    : fee.feedback;
+  return !fee.error ? `${formatAmountBasedOnLocale({ value: fee.value })} ${token}` : fee.feedback;
 };
 
-export const getSpaceSeparated = str => str.replace(/([A-Z])/g, ' $1');
+export const getSpaceSeparated = (str) => str.replace(/([A-Z])/g, ' $1');
 
 export default getTxDirectionConfig;
+
+export const trimBigintString = (data) => {
```
Comment (ManuGowda) [inline src/modules/transaction/utils/helpers.js:40]: why was this logic introduced?

**Review by soroushm — APPROVED** [review]
sign multisigniture worked
sign token transfer worked
sign message has issue (complain about hw)
sign legacy has fee problem
sign vote failed
register delegate needs token i couldn't verified
unlock is not tested

**Review by ikem-legend — APPROVED** [review]
@eniolam1000752 Registering multisignature account with the current account as one of the members fails

File: src/modules/token/fungible/components/SendForm/SendForm.js (hunk 21 above)
Comment (eniolam1000752) [reply src/modules/token/fungible/components/SendForm/SendForm.js:150]: an issue has been created for this https://github.com/LiskHQ/lisk-desktop/issues/4523

File: src/modules/legacy/components/Summary/Summary.js (hunk 18 above)
Comment (eniolam1000752) [reply src/modules/legacy/components/Summary/Summary.js:37]: for now minFee is wrong and would be addressed by this issue https://github.com/LiskHQ/lisk-desktop/issues/4529. A todo was supposed to be added here

File: src/modules/network/store/reducer.js (hunk 19 above)
Comment (eniolam1000752) [reply src/modules/network/store/reducer.js:56]: hmmmm though we now have a hook `useCommandSchema` that does the filtering and only returns an object whose key is the moduleCommand and value is the schema

File: src/modules/transaction/utils/helpers.js (hunk 25 above)
Comment (eniolam1000752) [reply src/modules/transaction/utils/helpers.js:40]: lisk-sdk is unable to parse the string representation of a big int let's say for example `1n`. So as a fix on the client end I had to introduce this function that recursively goes though the tx object and removes the `n` from any string represented bigInt value

File: src/modules/transaction/components/Overview/Overview.js (hunk 24 above)
Comment (eniolam1000752) [reply src/modules/transaction/components/Overview/Overview.js:126]: okay

File: src/modules/dpos/validator/store/actions/voting.js (hunk 16 above)
Comment (eniolam1000752) [reply src/modules/dpos/validator/store/actions/voting.js:117]: actually service returns votesSent as this and it contains account

```
  "data": {
    "account": {
      "address": "lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu",
      "publicKey": "aq02qkbb35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu", // Optional
      "name": "genesis_56", // Optional
      "votesUsed": 10
    },
    "votes": [
      {
        "delegateAddress": "lsk24cd35u4jdq8szo3ptrn47dsxwrnazyhhkg5eu",
        "amount": "1081560729258",
        "name": "liskhq" // Optional
      }
    ]
  },
  "meta": {
    "count": 10,
    "offset": 0,
    "total": 10,
  },
  "links": {}
}
```
